(function(){
  function baseRows(state){const mr=Array.isArray(state.data.marketRuntime)?state.data.marketRuntime:[];return mr.map((r,i)=>({rank:i+1,symbol:r.symbol||'--',price:r.price,oneD:r.change_1d,m1:r.m1_score,m7:r.m7_score,totalExposure:r.total_exposure||0,category:(r.category||'').toLowerCase()}));}
  function render(state){const el=MMUI.q('c2-all-stock-radar'); if(!el) return; let rows=baseRows(state); const f=state.radar; if(f.category!=='all') rows=rows.filter(r=>r.category===f.category); if(f.m7min!=='') rows=rows.filter(r=>(+r.m7||0)>=+f.m7min); if(f.m1min!=='') rows=rows.filter(r=>(+r.m1||0)>=+f.m1min); if(f.maxExposure!=='') rows=rows.filter(r=>(+r.totalExposure||0)<=+f.maxExposure);
  el.innerHTML=`<details><summary>Filter Weight Drawer</summary>alert/ranking/volatility/exposure weights (display only)</details><div class='search-row'><select id='radar-view'><option value='alerts'>Alerts</option><option value='m7'>M7 Ranking</option></select><select id='radar-category'><option>all</option><option>core</option><option>growth</option><option>defensive</option><option>income</option><option>speculative</option></select><input id='radar-m7min' placeholder='M7 min'><input id='radar-m1min' placeholder='M1 min'><input id='radar-maxexp' placeholder='max exposure'></div><div id='radar-alerts' class='muted'></div><div class='table-wrap'><table><thead><tr><th>rank</th><th>alert</th><th>symbol</th><th>price</th><th>1D</th><th>M1</th><th>M7</th><th>total exposure</th><th>expand</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.rank}</td><td>--</td><td>${r.symbol}</td><td>${MMUI.num(r.price)}</td><td>${MMUI.pct(r.oneD)}</td><td>${MMUI.num(r.m1)}</td><td>${MMUI.num(r.m7)}</td><td>${MMUI.num(r.totalExposure)}</td><td><button class='radar-expand' data-symbol='${r.symbol}'>+</button></td></tr><tr id='x-${r.symbol}' style='display:none'><td colspan='9'>M1/M7/M2/M6 details; M3/M8 placeholder</td></tr>`).join('')}</tbody></table></div>`;
 const alerts=MMAlertEngine.compute(rows); MMUI.q('radar-alerts').textContent=`movers: ${alerts.movers.join(', ')} | high exposure: ${alerts.warnings.join(', ')}`;
 el.querySelectorAll('.radar-expand').forEach(b=>b.onclick=()=>{const x=MMUI.q(`x-${b.dataset.symbol}`); x.style.display=x.style.display==='none'?'table-row':'none';});
 ['radar-category','radar-m7min','radar-m1min','radar-maxexp'].forEach(id=>MMUI.q(id)?.addEventListener('change',()=>MMState.set({radar:{...MMState.get().radar,category:MMUI.q('radar-category').value,m7min:MMUI.q('radar-m7min').value,m1min:MMUI.q('radar-m1min').value,maxExposure:MMUI.q('radar-maxexp').value}})));
 }
 window.MMModuleRadar={render};
})();
