// ============================================================
// M2 Section 7 FCN Interest Projection v2
// Entry rule: first coupon = entry + 41 days, cash-in = coupon + 3 days, next coupon +31 days.
// v2: force owns interest route after main engine fallback, so Pool Manual Ops cannot remain.
// ============================================================
(function(){
  if(window.__M2_INTEREST_PROJECTION_V2__) return;
  window.__M2_INTEREST_PROJECTION_V2__=true;
  const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
  const fmt=(v,d=2)=>n(v).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  let poolRows=[], selectedTemplate='all', projectionRows=[], mounted=false;
  const cfg={firstOffset:41,interval:31,cashBuffer:3,months:12};

  function css(){return `<style>
  #bottomQuery .ip-wrap{display:grid;grid-template-columns:280px 1fr;gap:12px;align-items:start}.ip-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:12px}.ip-title{font-size:16px;font-weight:950;margin-bottom:8px}.ip-sub{font-size:12px;color:#64748b;line-height:1.45;margin-bottom:10px}.ip-btns{display:grid;gap:8px}.ip-btn{border:1px solid #d8dde6;background:#fff;color:#111;border-radius:12px;padding:10px;text-align:left;font-weight:950;cursor:pointer}.ip-btn.active{background:#111;color:#fff;border-color:#111}.ip-tools{display:flex;flex-wrap:wrap;gap:8px;margin:8px 0}.ip-tools input,.ip-tools select{border:1px solid #cbd5e1;border-radius:10px;padding:8px;background:#fff}.ip-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.ip-kpi{border:1px solid #e5e7eb;border-radius:14px;background:#f8fafc;padding:10px}.ip-kpi label{display:block;font-size:11px;color:#64748b;font-weight:900}.ip-kpi b{font-size:20px}.ip-table-wrap{overflow:auto;border:1px solid #e5e7eb;border-radius:14px;margin-top:10px}.ip-table{width:100%;border-collapse:collapse;min-width:980px}.ip-table th,.ip-table td{border-bottom:1px solid #eee;padding:8px;text-align:left;font-size:12px;white-space:nowrap}.ip-table th{background:#fafafa;color:#475569;position:sticky;top:0}.ip-note{border:1px solid #f1df9a;background:#fffbe6;border-radius:12px;padding:10px;font-size:12px;line-height:1.6;margin:8px 0}.ip-json{background:#020617;color:#d1fae5;border-radius:14px;padding:10px;font-family:Consolas,monospace;font-size:12px;white-space:pre;overflow:auto;max-height:260px}.ip-empty{border:1px dashed #cbd5e1;background:#f8fafc;border-radius:12px;padding:12px;color:#64748b;margin-top:10px}@media(max-width:1100px){#bottomQuery .ip-wrap{grid-template-columns:1fr}.ip-grid{grid-template-columns:1fr 1fr}}@media(max-width:720px){.ip-grid{grid-template-columns:1fr}}
  </style>`}
  function first(...vals){return vals.find(v=>v!==undefined&&v!==null&&String(v)!=='')}
  function addDays(date,days){const d=new Date(date);d.setDate(d.getDate()+days);return d}
  function ymd(d){if(!d)return'';const x=new Date(d);return Number.isNaN(x.getTime())?'':x.toISOString().slice(0,10)}
  function ym(d){const s=ymd(d);return s?s.slice(0,7):''}
  function entryDate(f){return first(f.entry_time,f.created_time,f.date,f.entry_date,f.create_date)}
  function maturityDate(f){if(f.maturity_time)return f.maturity_time;const e=new Date(entryDate(f));if(Number.isNaN(e.getTime()))return'';e.setMonth(e.getMonth()+n(f.tenor,0));return e}
  function getBasket(f){return Array.isArray(f.basket)?f.basket:String(f.basket||'').split(/[,+/\s]+/).filter(Boolean)}
  function activePosition(f){return String(f.status||'active')==='active' && f.has_position!==false && f.is_portfolio!==false}
  async function loadPool(){try{const res=await fetch('../../data/fcn_pool.json',{cache:'no-store'});const data=await res.json();poolRows=(Array.isArray(data)?data:(data.rows||data.data||data.fcns||[]));}catch(e){poolRows=[];console.error(e)}}
  function templateRows(){const bank=document.getElementById('ipBank')?.value||'';const single=(document.getElementById('ipSingle')?.value||'').trim().toUpperCase();const custom=(document.getElementById('ipCustom')?.value||'').trim().toUpperCase();let rows=poolRows.filter(activePosition);if(selectedTemplate==='bank'&&bank)rows=rows.filter(f=>String(f.tw_bank||f.bank||'').includes(bank));if(selectedTemplate==='rayray')rows=rows.filter(f=>String(f.fcn_id||'').includes('睿睿'));if(selectedTemplate==='single'&&single)rows=rows.filter(f=>String(f.fcn_id||'').toUpperCase().includes(single));if(selectedTemplate==='custom'&&custom){const ids=custom.split(/[\n, ]+/).map(x=>x.trim()).filter(Boolean);rows=rows.filter(f=>ids.some(id=>String(f.fcn_id||'').toUpperCase().includes(id)));}return rows}
  function buildProjection(){cfg.firstOffset=n(document.getElementById('ipFirst')?.value,41);cfg.interval=n(document.getElementById('ipInterval')?.value,31);cfg.cashBuffer=n(document.getElementById('ipBuffer')?.value,3);cfg.months=n(document.getElementById('ipMonths')?.value,12);const start=new Date();const end=new Date();end.setMonth(end.getMonth()+cfg.months);const rows=[];templateRows().forEach(f=>{const e=new Date(entryDate(f));if(Number.isNaN(e.getTime()))return;const mat=new Date(maturityDate(f));const stop=Number.isNaN(mat.getTime())?end:mat;let coupon=addDays(e,cfg.firstOffset);let seq=1;while(coupon<=end && coupon<=stop && seq<=48){const cash=addDays(coupon,cfg.cashBuffer);if(cash>=start){const interest=n(f.amt,0)*n(f.rate,0)/100/12;rows.push({month:ym(cash),cash_in_date:ymd(cash),coupon_date:ymd(coupon),seq,fcn_id:f.fcn_id||'',bank:f.tw_bank||f.bank||'',issuer:f.bank||'',basket:getBasket(f).join('/'),currency:f.currency||'USD',amt:n(f.amt,0),rate:n(f.rate,0),interest});}coupon=addDays(coupon,cfg.interval);seq++;}}
    projectionRows=rows.sort((a,b)=>a.cash_in_date.localeCompare(b.cash_in_date)||a.fcn_id.localeCompare(b.fcn_id));}
  function monthlySummary(){const map={};projectionRows.forEach(r=>{const k=r.month+'|'+r.currency;map[k]=map[k]||{month:r.month,currency:r.currency,interest:0,count:0};map[k].interest+=r.interest;map[k].count++;});return Object.values(map).sort((a,b)=>a.month.localeCompare(b.month)||a.currency.localeCompare(b.currency))}
  function renderKpis(){const fcns=templateRows();const totalAmt=fcns.reduce((s,f)=>s+n(f.amt),0);const totalInterest=projectionRows.reduce((s,r)=>s+r.interest,0);const months=monthlySummary().length;return `<div class="ip-grid"><div class="ip-kpi"><label>FCN Count</label><b>${fcns.length}</b></div><div class="ip-kpi"><label>Principal</label><b>USD ${fmt(totalAmt,0)}</b></div><div class="ip-kpi"><label>Projection Rows</label><b>${projectionRows.length}</b></div><div class="ip-kpi"><label>Total Interest</label><b>USD ${fmt(totalInterest,2)}</b><div class="ip-sub">${months} 個 cash-in 月份</div></div></div>`}
  function renderTables(){const mon=monthlySummary();if(!projectionRows.length)return `<div class="ip-empty">目前模板沒有可推估資料。請確認 fcn_pool 是否有 active / has_position=true / entry_time。</div>`;return `<h3>7C. 月別總表</h3><div class="ip-table-wrap"><table class="ip-table"><thead><tr><th>Month</th><th>Currency</th><th>Count</th><th>Estimated Interest</th></tr></thead><tbody>${mon.map(r=>`<tr><td><b>${r.month}</b></td><td>${r.currency}</td><td>${r.count}</td><td>${r.currency} ${fmt(r.interest,2)}</td></tr>`).join('')}</tbody></table></div><h3 style="margin-top:14px">7D. FCN 明細表</h3><div class="ip-table-wrap"><table class="ip-table"><thead><tr><th>Cash-in</th><th>Coupon Date</th><th>#</th><th>FCN</th><th>Bank</th><th>Basket</th><th>Amt</th><th>Rate</th><th>Interest</th></tr></thead><tbody>${projectionRows.map(r=>`<tr><td>${r.cash_in_date}</td><td>${r.coupon_date}</td><td>${r.seq}</td><td><b>${esc(r.fcn_id)}</b></td><td>${esc(r.bank)}</td><td>${esc(r.basket)}</td><td>${r.currency} ${fmt(r.amt,0)}</td><td>${fmt(r.rate,2)}%</td><td>${r.currency} ${fmt(r.interest,2)}</td></tr>`).join('')}</tbody></table></div>`}
  function render(){const box=document.getElementById('bottomQuery');if(!box)return;buildProjection();box.innerHTML=css()+`<div class="ip-wrap"><aside class="ip-card"><div class="ip-title">7A. 快速模板</div><div class="ip-sub">按一下即可重算未來每月入帳利息。</div><div class="ip-btns">${btn('all','ALL 全部 FCN')}${btn('bank','By Bank 銀行別')}${btn('rayray','睿睿專區')}${btn('single','Single FCN')}${btn('custom','Custom 自訂')}</div><div class="ip-note">日期規則：第一次理論配息 = entry + 41 days；預估入帳 = 配息 + 3 days；之後每 31 days 一次。</div></aside><main class="ip-card"><div class="ip-title">7. FCN 利息推估</div><div class="ip-tools"><label>Bank <select id="ipBank"><option value="">全部</option><option>富邦</option><option>永豐</option></select></label><label>Single <input id="ipSingle" placeholder="FCN849N"></label><label>Months <input id="ipMonths" type="number" value="${cfg.months}"></label><label>First +days <input id="ipFirst" type="number" value="${cfg.firstOffset}"></label><label>Interval <input id="ipInterval" type="number" value="${cfg.interval}"></label><label>Cash buffer <input id="ipBuffer" type="number" value="${cfg.cashBuffer}"></label></div><textarea id="ipCustom" rows="2" style="width:100%;border:1px solid #cbd5e1;border-radius:10px;padding:8px" placeholder="Custom FCN IDs，用逗號或換行：FCN849N 睿睿, FCN981N 睿睿"></textarea><div class="ip-tools"><button id="ipRun">重新計算</button><button class="light" id="ipCopyJson">複製 JSON</button><button class="light" id="ipCopyCsv">複製 CSV</button></div><div id="ipResult">${renderKpis()}${renderTables()}<h3 style="margin-top:14px">7E. JSON Preview</h3><pre class="ip-json">${esc(JSON.stringify({template:selectedTemplate,config:cfg,rows:projectionRows},null,2))}</pre></div></main></div>`;bind();}
  function btn(k,label){return `<button class="ip-btn ${selectedTemplate===k?'active':''}" data-ip-template="${k}" type="button">${label}</button>`}
  function bind(){document.querySelectorAll('[data-ip-template]').forEach(b=>b.addEventListener('click',()=>{selectedTemplate=b.dataset.ipTemplate;render()}));['ipBank','ipSingle','ipCustom','ipMonths','ipFirst','ipInterval','ipBuffer'].forEach(id=>document.getElementById(id)?.addEventListener('input',()=>{setTimeout(render,0)}));document.getElementById('ipRun')?.addEventListener('click',render);document.getElementById('ipCopyJson')?.addEventListener('click',()=>navigator.clipboard?.writeText(JSON.stringify({template:selectedTemplate,config:cfg,rows:projectionRows},null,2)));document.getElementById('ipCopyCsv')?.addEventListener('click',()=>navigator.clipboard?.writeText(toCsv()));}
  function toCsv(){const head=['month','cash_in_date','coupon_date','seq','fcn_id','bank','basket','currency','amt','rate','interest'];return [head.join(','),...projectionRows.map(r=>head.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\n')}
  function setShell(){document.querySelectorAll('.menu-btn').forEach(b=>b.classList.toggle('active',b.dataset.module==='interest'));document.getElementById('m2HoldingZonesSubnav')?.classList.remove('show');document.getElementById('m2MaturityCashflowSubnav')?.classList.remove('show');document.getElementById('m2MarketFcnSubnav')?.classList.remove('show');const at=document.getElementById('activeTitle'),as=document.getElementById('activeSub'),bt=document.getElementById('bottomTitle'),bs=document.getElementById('bottomSub');if(at)at.textContent='7. FCN 利息推估';if(as)as.textContent='ALL / Bank / 睿睿 / Single / Custom 模板月配息推估';if(bt)bt.textContent='7. FCN 利息推估｜大型資訊查詢區';if(bs)bs.textContent='entry + 41 天首次配息，配息 +3 天入帳，之後每 31 天。';const rd=document.getElementById('rightDetail');if(rd)rd.innerHTML='<div class="flow-panel"><div class="flow-card" style="--accent:#2563eb"><div class="flow-label">Templates</div><div class="flow-value">5</div><div class="flow-sub">ALL / Bank / 睿睿 / Single / Custom</div></div><div class="flow-card" style="--accent:#0f766e"><div class="flow-label">First Coupon</div><div class="flow-value">+41d</div><div class="flow-sub">entry_time 起算</div></div><div class="flow-card" style="--accent:#f97316"><div class="flow-label">Cash In</div><div class="flow-value">+3d</div><div class="flow-sub">配息後 3 天入帳</div></div><div class="flow-card" style="--accent:#7c3aed"><div class="flow-label">Next</div><div class="flow-value">31d</div><div class="flow-sub">後續每 31 天</div></div></div>';const ri=document.getElementById('rightInsight');if(ri)ri.innerHTML='<div class="decision-note"><b>第七區用途：</b>用 fcn_pool.json 直接推估未來每月 FCN 利息入帳。月別歸屬以 cash_in_date 為準，不以 coupon_date 為準。</div>';}
  async function mount(force=false){const title=document.getElementById('activeTitle')?.textContent||'';const active=document.querySelector('.menu-btn.active')?.dataset.module;const box=document.getElementById('bottomQuery');if(!box)return;if(!force && active!=='interest' && !title.includes('FCN 利息推估'))return;setShell();if(mounted && !force && box.querySelector('.ip-wrap'))return;mounted=true;box.innerHTML='<div class="muted">FCN 利息推估載入中...</div>';await loadPool();render();}
  function requestMount(){mounted=false;setTimeout(()=>mount(true),40);setTimeout(()=>mount(true),220);setTimeout(()=>mount(true),650)}
  document.addEventListener('click',ev=>{if(ev.target.closest('[data-module="interest"]'))requestMount();},true);
  const obs=new MutationObserver(()=>{const active=document.querySelector('.menu-btn.active')?.dataset.module;const title=document.getElementById('activeTitle')?.textContent||'';const box=document.getElementById('bottomQuery');if((active==='interest'||title.includes('FCN 利息推估'))&&box&&!box.querySelector('.ip-wrap'))mount(true);});
  if(document.body)obs.observe(document.body,{childList:true,subtree:true,characterData:true});
  setInterval(()=>{const active=document.querySelector('.menu-btn.active')?.dataset.module;const box=document.getElementById('bottomQuery');if(active==='interest'&&box&&!box.querySelector('.ip-wrap'))mount(true);},900);
  window.M2InterestProjection={mount:()=>mount(true),rerender:render,loadPool};
})();
