// ============================================================
// MM/M2 新作戰中心 Engine v0.4.3
// Patch: Type-aware maturity payoff logic + Holding Zones left subnav display
// ============================================================
import { runM2HealthEngine } from '../../core/m2_health_engine_v1.js';
import { renderLegacyHoldingZones } from './m2_holding_zones_legacy_cards.js';

const TARGET_BANK={富邦:900000,永豐:500000};
const STOCK_CAP={core:500000,growth:300000,defensive:300000,income:200000,speculative:30000};
const CAP_EXCEPTION={NVDA:700000,TSM:700000,SMH:700000,GOOG:700000};
const BUCKET_COLOR={'長期穩定現金流':'#2563eb','合理投資型':'#0f766e','積極單':'#f97316','短期投機單':'#7c3aed','其他':'#94a3b8'};
const MODULE_META={summary:['1. Summary Dashboard','資金水位 / 配置 / 健康 / 預計出場'],zones:['2. Holding Zones','到期專區 / 預計提前到期 / Danger / Watch / Healthy'],planning:['3. Maturity Cashflow','Planner A/B/C/D/E0：到期資金流與佈局重建'],market:['4. Market FCN Analysis','市場單分析與推薦，先做容量與配置判斷，後續接 M8'],management:['5. FCN / Stock Management','完整 FCN 查詢 + 股票風險分析'],pool:['6. Pool Manual Ops','手動建新單 / 編輯 / 複製 / Soft Delete / 匯出']};
let runtime=null, plannerRows=[], poolMap={}, currentModule='summary', stockCapacityRowsData=[];
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const fmt=(v,d=0)=>n(v).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=(v,b,d=1)=>b?fmt(v/b*100,d):'0';
const sum=list=>list.reduce((s,x)=>s+n(x.amt),0);
function bucket(x){const r=n(x.rate),t=n(x.tenor);if(t<=6&&r>20.99)return'短期投機單';if(r>=21&&r<=25)return'積極單';if(r>=18&&r<=20.99)return'合理投資型';if(r>=12&&r<=17.99)return'長期穩定現金流';return'其他'}
function kpi(k,v,d,a,extra=''){return `<div class="kpi" style="--accent:${a}"><div class="kpi-label">${k}</div><div class="kpi-value">${v}</div><div class="kpi-sub">${d}</div>${extra}</div>`}
function flowCard(k,v,d,a){return `<div class="flow-card" style="--accent:${a}"><div class="flow-label">${k}</div><div class="flow-value">${v}</div><div class="flow-sub">${d}</div></div>`}
function metricBlock(t,m,s,a){return `<div class="mini-metric" style="--accent:${a}"><div class="metric-title">${t}</div><div class="metric-main">${m}</div><div class="metric-sub">${s}</div></div>`}
function listCard(title,body,cls=''){return `<div class="list-card ${cls}"><b>${title}</b><br>${body}</div>`}
function conic(parts,total){let cur=0;return parts.map(p=>{const deg=total?p.amt/total*360:0;const s=`${BUCKET_COLOR[p.k]||'#ddd'} ${cur}deg ${cur+deg}deg`;cur+=deg;return s}).join(',')}
function miniBar(rows,total){return `<div class="mini-stack">${rows.map(r=>`<div><div class="mini-line"><span style="--bar:${r.color};width:${Math.min(100,total?r.value/total*100:0)}%"></span></div><span class="kpi-chip">${r.label} ${total?fmt(r.value/total*100,0):0}%</span></div>`).join('')}</div>`}
function dateValue(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
function entryDateRaw(f){return f.entry_date||f.create_date||f.trade_date||f.start_date||f.date||f.created_at||f.issue_date||null}
function daysSinceEntry(f){const d=dateValue(entryDateRaw(f));if(!d)return null;return Math.floor((Date.now()-d.getTime())/86400000)}
function stockRatio(s){const cur=n(s.price_now??s.current_price??s.spot??s.now,NaN);const ent=n(s.entry_price??s.entry??s.start_price,NaN);return Number.isFinite(cur)&&Number.isFinite(ent)&&ent>0?cur/ent:null}
function worstEntryRatio(f){const ratios=(f.stocks||[]).map(stockRatio).filter(x=>x!==null);if(!ratios.length)return null;return Math.min(...ratios)}
function isEarlyExitCandidate(f){const d=daysSinceEntry(f);const r=worstEntryRatio(f);return d!==null&&d>=27&&r!==null&&r>1}
function productType(f){return String(f.type||f.fcn_type||f.note_type||f.structure||f.product_type||'').toUpperCase().includes('AKI')?'AKI':'EKI'}
function stockNow(s){return n(s.price_now??s.current_price??s.spot??s.now,NaN)}
function stockKI(s){return n(s.ki_price??s.ki??s.knock_in_price??s.lower_barrier_price??s.barrier_price,NaN)}
function stockStrike(s){return n(s.strike_price??s.strike??s.execution_price??s.exec_price,NaN)}
function terminalBelowKI(s){const cur=stockNow(s),ki=stockKI(s);return Number.isFinite(cur)&&Number.isFinite(ki)&&ki>0?cur<ki:null}
function terminalBelowStrike(s){const cur=stockNow(s),strike=stockStrike(s);return Number.isFinite(cur)&&Number.isFinite(strike)&&strike>0?cur<strike:null}
function everBarrierBreached(s){const v=s.period_barrier_breached??s.barrier_breached??s.ki_breached??s.has_knock_in??s.knock_in_event??s.touched_ki; if(v===true||v==='true'||v==='Y'||v==='yes'||v===1)return true;if(v===false||v==='false'||v==='N'||v==='no'||v===0)return false;return null}
function projectedMaturityDate(f){const e=dateValue(entryDateRaw(f));const months=n(f.period??f.tenor??f.tenor_months,NaN);if(!e||!Number.isFinite(months))return null;const d=new Date(e);d.setMonth(d.getMonth()+months);d.setDate(d.getDate()+7);return d.toISOString().slice(0,10)}
function hasReachedProjectedMaturity(f){const p=projectedMaturityDate(f);const d=dateValue(p);return d?Date.now()>=d.getTime():false}
function maturityPayoffState(f){const type=productType(f),projected=projectedMaturityDate(f);if(!hasReachedProjectedMaturity(f)){return{maturity_state:'maturity_observe',maturity_reason:`尚未進入 entry + period + 7 days 的實際滿期結算日（${projected||'日期不足'}），列為預計滿期 / 觀察。`,maturity_type_rule:type,period_barrier_breached:null,terminal_barrier_breached:null,terminal_all_above_strike:false,terminal_any_below_strike:false,projected_maturity_date:projected}}
const stocks=f.stocks||[];const terminal=stocks.map(s=>({belowKI:terminalBelowKI(s),belowStrike:terminalBelowStrike(s),breached:everBarrierBreached(s)}));const anyBelowKI=terminal.some(x=>x.belowKI===true);const anyBelowStrike=terminal.some(x=>x.belowStrike===true);const allAboveStrike=terminal.length&&terminal.every(x=>x.belowStrike===false);const anyDataMissing=terminal.some(x=>x.belowKI===null||x.belowStrike===null||(type==='AKI'&&x.breached===null));let state='maturity_observe',reason='已進入實際滿期結算日，但資料不足；先列入預計滿期 / 觀察。';if(type==='EKI'){if(anyBelowKI){state='stock_delivery_risk';reason='EKI：滿期時任一股票破下限價，列為接股可能。';}else if(terminal.length&&!terminal.some(x=>x.belowKI===null)){state='safe_maturity';reason='EKI：滿期時至少一支 / 全部可判定未破下限價，列為滿期安全。';}}
else{const anyBreached=terminal.some(x=>x.breached===true);const noneBreached=terminal.length&&terminal.every(x=>x.breached===false);if(anyBelowKI){state='stock_delivery_risk';reason='AKI：期末任一股票破下限價，列為接股可能。';}else if(anyBreached&&anyBelowStrike){state='stock_delivery_risk';reason='AKI：期間曾破下限價，且期末任一股票低於執行價，列為接股可能。';}else if(noneBreached&&!anyBelowKI&&!anyDataMissing){state='safe_maturity';reason='AKI：期間未破下限價，且期末未破下限價，列為滿期安全。';}else if(anyBreached&&allAboveStrike){state='safe_maturity';reason='AKI：期間曾破下限價，但期末每一隻股票都高於執行價，列為滿期安全。';}}
return{maturity_state:state,maturity_reason:reason,maturity_type_rule:type,period_barrier_breached:type==='AKI'?terminal.some(x=>x.breached===true):null,terminal_barrier_breached:anyBelowKI,terminal_all_above_strike:!!allAboveStrike,terminal_any_below_strike:anyBelowStrike,projected_maturity_date:projected}}
function getGroups(){const active=plannerRows,base=active.filter(x=>x.planner_tag==='Planning Base'),ready=active.filter(x=>x.planner_tag==='Early Exit Ready'),maturity=active.filter(x=>x.planner_tag==='30D Maturity'),candidate=active.filter(x=>x.planner_tag==='Early Exit Candidate'),cash=[...ready,...maturity,...candidate];return{active,base,ready,maturity,candidate,cash,hard:[...ready,...maturity]}}
function buildPlannerRows(fcns){plannerRows=fcns.map(f=>{const d=f.maturity?.days_to_maturity??9999;let tag='Planning Base';const ratio=worstEntryRatio(f);const days=daysSinceEntry(f);const payoff=maturityPayoffState(f);if(f.early_exit_ready)tag='Early Exit Ready';else if(d<=30)tag='30D Maturity';else if(isEarlyExitCandidate(f))tag='Early Exit Candidate';return{...f,...payoff,planner_tag:tag,excluded:tag!=='Planning Base',early_exit_candidate_rule:'entry+27_and_worst_of_over_100pct_entry',early_exit_candidate_days_since_entry:days,early_exit_candidate_worst_entry_ratio:ratio,early_exit_candidate_worst_entry_pct:ratio===null?null:ratio*100}})}
function buildStockCapacityRows(){const stockMap={};plannerRows.forEach(f=>(f.basket||[]).forEach(s=>{if(!stockMap[s])stockMap[s]={symbol:s,active:0,release:0,base:0,count:0,danger:0,watch:0};stockMap[s].active+=n(f.amt);stockMap[s].count++;if(f.excluded)stockMap[s].release+=n(f.amt);else stockMap[s].base+=n(f.amt);const st=(f.stocks||[]).find(x=>x.symbol===s);if(st?.stock_health==='danger')stockMap[s].danger++;if(st?.stock_health==='watch')stockMap[s].watch++}));stockCapacityRowsData=Object.values(stockMap).map(r=>{const meta=poolMap[r.symbol]||{},category=meta.category||'growth',max=CAP_EXCEPTION[r.symbol]||STOCK_CAP[category]||300000,staticRemain=Math.max(0,max-r.active),dynamic=Math.max(0,max-r.base);let light='GREEN',comment='可正常布局';if(r.danger>0){light='RED';comment='有 danger 紀錄，先處理風險'}else if(dynamic<=0){light='RED';comment='超過上限'}else if(dynamic/max<0.2||r.watch>0){light='YELLOW';comment='接近滿載或有 watch'}return{...r,category,max,staticRemain,dynamic,light,comment}}).sort((a,b)=>a.light.localeCompare(b.light)||b.dynamic-a.dynamic)}
function allocParts(list){const targets={'長期穩定現金流':40,'合理投資型':30,'積極單':20,'短期投機單':10,'其他':0};return Object.keys(targets).map(k=>({k,target:targets[k],amt:sum(list.filter(x=>bucket(x)===k))}))}
function compactFCN(f){return `<div class="compact-fcn"><div><div class="compact-main">${f.fcn_id}</div><div class="compact-sub">${(f.basket||[]).join(' / ')}｜Worst ${f.worst_of||'-'}</div></div><div class="compact-amt">USD ${fmt(f.amt)}</div><div><span class="pill ${f.fcn_health==='danger'?'pill-bad':f.fcn_health==='watch'?'pill-warn':'pill-good'}">${f.fcn_health||'-'}</span></div><button class="detail-toggle" type="button">明細</button><div class="fcn-more">Bank: ${f.tw_bank||''}｜Rate ${fmt(f.rate,2)}%｜Tenor ${f.tenor||''}M｜Tag ${f.planner_tag}<br>Decision: ${f.decision_label||''}<br>Days to maturity: ${f.maturity?.days_to_maturity??'-'}｜Early Exit ${f.early_exit_remark_count??0}/${f.early_exit_total_count??0}</div></div>`}
function bindDetailToggles(){document.querySelectorAll('.detail-toggle').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.compact-fcn')?.classList.toggle('open')))}
function renderTopDashboard(){const g=getGroups(),parts=allocParts(g.active),total=sum(g.active)||1,bankF=sum(g.active.filter(x=>(x.tw_bank||'').includes('富邦'))),bankS=sum(g.active.filter(x=>(x.tw_bank||'').includes('永豐'))),cashTotal=sum(g.cash)||1;topDashboard.innerHTML=[kpi('FCN 資金水位',`USD ${fmt(sum(g.active))}`,`${g.active.length} 檔｜富邦 ${fmt(bankF)} / 永豐 ${fmt(bankS)}`,'#2563eb',miniBar([{label:'富邦',value:bankF,color:'#2563eb'},{label:'永豐',value:bankS,color:'#0f766e'}],sum(g.active))),kpi('本月預計出場',`USD ${fmt(sum(g.cash))}`,`到期 ${fmt(sum(g.maturity))}｜提前 ${fmt(sum(g.ready))}｜候選 ${fmt(sum(g.candidate))}`,'#f97316',miniBar([{label:'到期',value:sum(g.maturity),color:'#dc2626'},{label:'提前',value:sum(g.ready),color:'#0f766e'},{label:'候選',value:sum(g.candidate),color:'#f97316'}],cashTotal)),kpi('健康狀態',`${runtime.danger.length+runtime.watch.length} 需看`,`Danger ${runtime.danger.length}｜Watch ${runtime.watch.length}｜Healthy ${runtime.healthy.length}`,'#dc2626',miniBar([{label:'Danger',value:runtime.danger.length,color:'#dc2626'},{label:'Watch',value:runtime.watch.length,color:'#f97316'},{label:'Healthy',value:runtime.healthy.length,color:'#0f766e'}],Math.max(1,runtime.total))),kpi('Planning Base',`USD ${fmt(sum(g.base))}`,`${g.base.length} 檔｜扣除本月出場後母體`,'#0f766e'),kpi('配置主軸',parts.map(p=>`${p.k.slice(0,2)} ${fmt(p.amt/total*100,0)}%`).join('｜'),'目前 active 配置粗覽','#7c3aed',miniBar(parts.map(p=>({label:p.k.slice(0,2),value:p.amt,color:BUCKET_COLOR[p.k]})),total)),kpi('系統模式','Read-only','不改舊 M2 / Planner，不寫回資料','#64748b')].join('')}
function setModule(m){currentModule=m;document.querySelectorAll('.menu-btn').forEach(b=>b.classList.toggle('active',b.dataset.module===m));document.getElementById('m2HoldingZonesSubnav')?.classList.toggle('show',m==='zones');const meta=MODULE_META[m];activeTitle.textContent=meta[0];activeSub.textContent=meta[1];bottomTitle.textContent=`${meta[0]}｜大型資訊查詢區`;bottomSub.textContent=meta[1];renderCurrentModule()}
function renderCurrentModule(){if(!runtime)return;({summary:renderSummary,zones:renderZones,planning:renderPlanning,market:renderMarket,management:renderManagement,pool:renderPool}[currentModule]||renderSummary)();bindDetailToggles();bindFilters()}
function renderSummary(){const g=getGroups();rightDetail.innerHTML=`<div class="flow-panel">${flowCard('Active',`${g.active.length} / USD ${fmt(sum(g.active))}`,'目前持倉','#2563eb')}${flowCard('Expected Exit',`${g.cash.length} / USD ${fmt(sum(g.cash))}`,'本月預計出場','#f97316')}${flowCard('Planning Base',`${g.base.length} / USD ${fmt(sum(g.base))}`,'真正分析母體','#0f766e')}${flowCard('Risk',`${runtime.danger.length+runtime.watch.length}`,'Danger + Watch','#dc2626')}</div>`;rightInsight.innerHTML=`<div class="decision-note">M2 Summary 要一眼看完：現在有多少 FCN、健康度如何、本月預計釋放多少資金，以及釋放來源。下一步配置必須以 Planning Base 為母體，不是拿 Active 全部直接分析。</div>`;bottomQuery.innerHTML=`<div class="grid-3"><div class="panel"><h3>本月出場來源</h3>${listCard('30D Maturity',`${g.maturity.length} 檔｜USD ${fmt(sum(g.maturity))}`)}${listCard('Early Exit Ready',`${g.ready.length} 檔｜USD ${fmt(sum(g.ready))}`)}${listCard('Early Exit Candidate',`${g.candidate.length} 檔｜USD ${fmt(sum(g.candidate))}`)}</div><div class="panel"><h3>銀行資金水位</h3>${Object.keys(TARGET_BANK).map(b=>{const a=sum(g.active.filter(x=>(x.tw_bank||'').includes(b)));return listCard(b,`Active USD ${fmt(a)}｜Target USD ${fmt(TARGET_BANK[b])}｜Util ${pct(a,TARGET_BANK[b])}%`)}).join('')}</div><div class="panel"><h3>健康摘要</h3>${listCard('到期專區',`${runtime.maturity_zone.length} 檔`)}${listCard('Danger / Watch',`${runtime.danger.length} / ${runtime.watch.length} 檔`)}${listCard('Healthy',`${runtime.healthy.length} 檔`)}</div></div>`}
function renderZones(){renderLegacyHoldingZones({runtime,groups:getGroups(),rightDetail,rightInsight,bottomQuery})}
function renderBrokerBlock(){const g=getGroups();return `<div class="broker-grid">${Object.keys(TARGET_BANK).map(b=>{const target=TARGET_BANK[b],cur=g.active.filter(x=>(x.tw_bank||'').includes(b)),base=g.base.filter(x=>(x.tw_bank||'').includes(b)),exit=g.cash.filter(x=>(x.tw_bank||'').includes(b)),activeAmt=sum(cur),baseAmt=sum(base),exitAmt=sum(exit),future=Math.max(0,target-baseAmt);return `<div class="broker-card"><div class="broker-head"><div><b>${b}</b><div class="muted">Future Available</div></div><div class="broker-avail">USD ${fmt(future)}</div></div><div class="broker-metrics">${metricBlock('出場',`${exit.length} / USD ${fmt(exitAmt)}`,`${pct(exitAmt,activeAmt)}% Active`,'#f97316')}${metricBlock('剩餘母體',`${base.length} / USD ${fmt(baseAmt)}`,`${pct(baseAmt,activeAmt)}% Active`,'#0f766e')}${metricBlock('原母體',`${cur.length} / USD ${fmt(activeAmt)}`,`${pct(activeAmt,target)}% Target`,'#2563eb')}${metricBlock('可補',`USD ${fmt(future)}`,`${pct(future,target)}% open`,'#7c3aed')}</div></div>`}).join('')}</div>`}
function renderAllocBlock(){const g=getGroups(),base=g.base,total=sum(base)||1,parts=allocParts(base);return `<div class="alloc-layout"><div class="panel"><b>Planning Base 結構</b><div class="pie" style="background:conic-gradient(${conic(parts,total)})"></div>${parts.map(p=>`<div class="legend-row"><span><i class="legend-dot" style="background:${BUCKET_COLOR[p.k]}"></i>${p.k}</span><b>${fmt(p.amt/total*100,1)}%</b></div>`).join('')}</div><div class="panel"><b>Real vs Target</b>${parts.map(p=>{const bp=p.amt/total*100,gap=bp-p.target;return `<div class="alloc-row"><div><b>${p.k}</b><div class="muted">USD ${fmt(p.amt)} / ${fmt(bp,1)}%</div><div class="bar"><span style="--bar:${BUCKET_COLOR[p.k]};width:${Math.min(100,bp)}%"></span></div></div><div><b>Target ${p.target}%</b><div class="muted">Gap ${fmt(gap,1)}%</div></div></div>`}).join('')}</div><div class="panel"><div class="interpret-box"><div class="interpret-title">Planning Logic</div>此區是 m2_planner A/B/C/D/E0 的位置，負責到期資金流與重建佈局，不應佔滿整個 M2。</div></div></div>`}
function renderPlanning(){const g=getGroups();rightDetail.innerHTML=`<div class="flow-panel">${flowCard('Cash-in',`${g.cash.length} / USD ${fmt(sum(g.cash))}`,'本月預計釋放','#f97316')}${flowCard('Hard Release',`${g.hard.length} / USD ${fmt(sum(g.hard))}`,'到期 + ready','#dc2626')}${flowCard('Soft Candidate',`${g.candidate.length} / USD ${fmt(sum(g.candidate))}`,'預計提前到期候選','#b9770e')}${flowCard('Planning Base',`${g.base.length} / USD ${fmt(sum(g.base))}`,'扣除後母體','#0f766e')}</div>`;rightInsight.innerHTML=`<div class="decision-note">第3區才是 Planner 的主場：A 出場總覽、B 銀行容量、C 配置重建、D 單股容量、E0 出場明細。這裡用來回答：這個月會釋放多少錢、從哪裡來、釋放後該補哪裡。</div>`;bottomQuery.innerHTML=`${renderBrokerBlock()}<div style="height:12px"></div>${renderAllocBlock()}<div style="height:12px"></div><div class="cash-grid"><div class="cash-card"><div class="cash-title">Hard Release</div>${g.hard.map(compactFCN).join('')||'<div class="muted">none</div>'}</div><div class="cash-card"><div class="cash-title">Soft Candidate</div>${g.candidate.map(compactFCN).join('')||'<div class="muted">none</div>'}</div><div class="cash-card"><div class="cash-title">Planning Base</div>${g.base.slice(0,12).map(compactFCN).join('')}</div></div>`}
function evaluateInquiry(){const basket=(document.getElementById('inqBasket')?.value||'').toUpperCase().split(/[,+/\s]+/).map(x=>x.trim()).filter(Boolean),amt=n(document.getElementById('inqAmount')?.value,0),coupon=n(document.getElementById('inqCoupon')?.value,0),tenor=n(document.getElementById('inqTenor')?.value,12),bank=document.getElementById('inqBank')?.value||'富邦';const f={rate:coupon,tenor};const bkt=bucket(f);const stockLines=basket.map(s=>{const row=stockCapacityRowsData.find(x=>x.symbol===s);const dyn=row?row.dynamic:0;const after=dyn-amt;const light=!row?'UNKNOWN':after<0?'RED':after<row.max*0.2?'YELLOW':'GREEN';return{symbol:s,row,dyn,after,light}});const bankBase=sum(getGroups().base.filter(x=>(x.tw_bank||'').includes(bank))),bankFuture=Math.max(0,TARGET_BANK[bank]-bankBase),bankAfter=bankFuture-amt;const red=stockLines.filter(x=>x.light==='RED').length,unknown=stockLines.filter(x=>x.light==='UNKNOWN').length;let decision='可研究';let cls='pill-good';if(red||bankAfter<0){decision='不建議 / 超容量';cls='pill-bad'}else if(unknown||stockLines.some(x=>x.light==='YELLOW')){decision='小額 / 需確認';cls='pill-warn'}inqResult.innerHTML=`<div class="decision-note"><span class="pill ${cls}">${decision}</span><br>Bucket：<b>${bkt}</b>｜Bank：<b>${bank}</b>｜Amount：USD <b>${fmt(amt)}</b>｜Coupon：<b>${fmt(coupon,2)}%</b>｜Tenor：<b>${tenor}M</b><br>銀行未來可用：USD ${fmt(bankFuture)} → 下單後 USD ${fmt(bankAfter)}。${unknown?' 有標的不在 pool30 / capacity 表中，需人工確認。':''}</div><div class="table-wrap"><table><thead><tr><th>Stock</th><th>Current Dynamic</th><th>After Order</th><th>Light</th><th>Comment</th></tr></thead><tbody>${stockLines.map(x=>`<tr class="${x.light==='RED'?'row-bad':x.light==='YELLOW'?'row-warn':'row-good'}"><td><b>${x.symbol}</b></td><td>${x.row?'USD '+fmt(x.dyn):'N/A'}</td><td>${x.row?'USD '+fmt(x.after):'N/A'}</td><td><span class="pill ${x.light==='RED'?'pill-bad':x.light==='YELLOW'?'pill-warn':'pill-good'}">${x.light}</span></td><td>${x.row?x.row.comment:'未在目前 FCN / pool30 容量表'}</td></tr>`).join('')}</tbody></table></div>`}
function renderMarket(){rightDetail.innerHTML=`<div class="flow-panel">${flowCard('Inquiry Desk','Ready','先做容量 / 配置 / 銀行判斷','#2563eb')}${flowCard('M8 Compare','Next','待接 fair rate','#7c3aed')}${flowCard('Market History','Next','待接 market_fcn_history','#0f766e')}${flowCard('Recommendation','Draft','先輸出可研究 / 小額 / 不建議','#f97316')}</div>`;rightInsight.innerHTML=`<div class="decision-note">第4區先把市場單分析的骨架做正確：先判斷這張詢價單會不會超單股容量、是否符合銀行可用額度、屬於哪個 bucket。下一步再接 M8 fair rate 與 market coupon。</div>`;bottomQuery.innerHTML=`<div class="grid-2"><div class="panel"><h3>Inquiry Desk｜新詢價單判斷</h3><div class="table-tools"><input id="inqBasket" placeholder="Basket: NVDA,TSM,MU"><input id="inqCoupon" type="number" step="0.01" placeholder="Coupon %"><input id="inqTenor" type="number" step="1" placeholder="Tenor 月"><input id="inqAmount" type="number" step="1000" placeholder="Amount USD"><select id="inqBank"><option>富邦</option><option>永豐</option></select><button id="inqRun" type="button">判斷</button></div><div id="inqResult" class="muted">輸入 basket / coupon / tenor / amount 後按判斷。</div></div><div class="panel"><h3>Market Coupon Compare</h3><div class="muted">下一階段接 M8：Market Coupon / M8 Fair / Gap / Template。現在先完成容量與作戰流程。</div></div></div>`;document.getElementById('inqRun')?.addEventListener('click',evaluateInquiry)}
function renderManagement(){rightDetail.innerHTML=`<div class="flow-panel">${flowCard('FCN Rows',plannerRows.length,'完整 FCN 查詢母體','#2563eb')}${flowCard('Stock Rows',stockCapacityRowsData.length,'股票風險 + 容量','#0f766e')}${flowCard('Danger Stocks',stockCapacityRowsData.filter(x=>x.light==='RED').length,'需優先看','#dc2626')}${flowCard('Watch Stocks',stockCapacityRowsData.filter(x=>x.light==='YELLOW').length,'接近滿載或 watch','#f97316')}</div>`;rightInsight.innerHTML=`<div class="decision-note">第5區合併 m2_planner E 與 m2 的股票風險分析。這裡是查詢與風險管理，不是手動新增修改。</div>`;bottomQuery.innerHTML=`<div class="table-tools"><input id="fcnSearch" placeholder="搜尋 FCN / Stock / Bank"><select id="fcnTagFilter"><option value="all">Planner Tag: All</option><option>Planning Base</option><option>30D Maturity</option><option>Early Exit Ready</option><option>Early Exit Candidate</option></select><select id="stockLightFilter"><option value="all">Stock Light: All</option><option>GREEN</option><option>YELLOW</option><option>RED</option></select></div><div id="managementTables"></div>`;renderManagementTables()}
function renderManagementTables(){const q=(document.getElementById('fcnSearch')?.value||'').toUpperCase(),tag=document.getElementById('fcnTagFilter')?.value||'all',light=document.getElementById('stockLightFilter')?.value||'all';const stocks=stockCapacityRowsData.filter(x=>(light==='all'||x.light===light)&&(x.symbol.includes(q)||x.category.toUpperCase().includes(q)));const fcns=plannerRows.filter(x=>(tag==='all'||x.planner_tag===tag)&&(`${x.fcn_id} ${x.tw_bank} ${(x.basket||[]).join(' ')}`.toUpperCase().includes(q)));managementTables.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Stock</th><th>Category</th><th>Max</th><th>Active</th><th>Exit Release</th><th>Planning Base</th><th>Static Rem.</th><th>Dynamic</th><th>Light</th><th>Comment</th></tr></thead><tbody>${stocks.map(x=>`<tr class="${x.light==='RED'?'row-bad':x.light==='YELLOW'?'row-warn':'row-good'}"><td><b>${x.symbol}</b></td><td>${x.category}</td><td>USD ${fmt(x.max)}</td><td>USD ${fmt(x.active)}</td><td>USD ${fmt(x.release)}</td><td>USD ${fmt(x.base)}</td><td>USD ${fmt(x.staticRemain)}</td><td>USD ${fmt(x.dynamic)}</td><td><span class="pill ${x.light==='GREEN'?'pill-good':x.light==='YELLOW'?'pill-warn':'pill-bad'}">${x.light}</span></td><td>${x.comment}</td></tr>`).join('')}</tbody></table></div><div style="height:12px"></div>${renderFCNTable(fcns)}`}
function renderFCNTable(rows=plannerRows){return `<div class="table-wrap"><table><thead><tr><th>FCN ID</th><th>Bank</th><th>Amount</th><th>Rate</th><th>Tenor</th><th>Basket</th><th>Worst-of</th><th>Health</th><th>Planner Tag</th><th>Days to Maturity</th></tr></thead><tbody>${rows.map(x=>`<tr class="${x.fcn_health==='danger'?'row-bad':x.fcn_health==='watch'?'row-warn':'row-good'}"><td><b>${x.fcn_id}</b></td><td>${x.tw_bank||''}</td><td>USD ${fmt(x.amt)}</td><td>${fmt(x.rate,2)}%</td><td>${x.tenor||''}M</td><td>${(x.basket||[]).join(' / ')}</td><td>${x.worst_of||''}</td><td>${x.maturity_state||x.decision_label||''}</td><td>${x.planner_tag}</td><td>${x.maturity?.days_to_maturity??'-'}</td></tr>`).join('')}</tbody></table></div>`}
function renderPool(){rightDetail.innerHTML=`<div class="note">第6區來源是舊 m2 / 6. FCN Pool 管理。此區未來放手動建新單、編輯、複製、Soft Delete、匯出。</div>`;rightInsight.innerHTML=`<div class="decision-note">這是後台作業區，不應混在 Summary 或 Planner。新版會先把手動鍵新單流程整理乾淨，再考慮寫回。</div>`;bottomQuery.innerHTML=`<div class="grid-3"><div class="panel"><h3>手動建新單</h3><div class="table-tools"><input placeholder="fcn_id"><input placeholder="basket"><input placeholder="amount"><input placeholder="coupon"><select><option>active</option><option>draft</option></select></div><div class="muted">待搬 m2 6.2 表單。</div></div><div class="panel"><h3>FCN 清單</h3><div class="muted">待搬 m2 6.1 清單 / 搜尋 / filter</div></div><div class="panel"><h3>匯出 / Soft Delete</h3><button class="light">匯出 JSON</button> <button class="light">Soft Delete</button><div class="muted" style="margin-top:8px">保留舊 M2 作業邏輯，暫不寫回。</div></div></div>`}
function bindMenu(){document.querySelectorAll('.menu-btn').forEach(btn=>btn.addEventListener('click',()=>setModule(btn.dataset.module)))}
function bindFilters(){['fcnSearch','fcnTagFilter','stockLightFilter'].forEach(id=>{const el=document.getElementById(id);if(el)el.oninput=renderManagementTables;if(el)el.onchange=renderManagementTables})}
async function loadData(){try{runtimeMeta.textContent='載入資料中...';const [poolRes,marketRes,pool30Res]=await Promise.all([fetch('../../data/fcn_pool.json'),fetch('../../data/market_runtime.json'),fetch('../../data/pool30.json')]);const fcnPool=await poolRes.json(),marketRuntime=await marketRes.json(),pool30=await pool30Res.json();poolMap={};pool30.forEach(p=>poolMap[p.symbol]=p);runtime=runM2HealthEngine({fcnPool,marketRuntime:marketRuntime.rows||marketRuntime,pool30});buildPlannerRows(runtime.fcns);buildStockCapacityRows();renderTopDashboard();renderCurrentModule();runtimeMeta.innerHTML=`最後更新：${marketRuntime.generated_at||'unknown'}｜Active FCN ${runtime.total} 檔｜Stock Exposure ${runtime.stockMap.length} 檔`;}catch(err){console.error(err);runtimeMeta.innerHTML=`<span class="bad">載入失敗：${err.message}</span>`}}
runBtn.addEventListener('click',loadData);reloadBtn.addEventListener('click',loadData);bindMenu();loadData();

