// ============================================================
// MM/M2 新作戰中心 Engine v0.4.9
// Patch: Market FCN M2 Gate + M8 Template Coverage
// ============================================================
import { runM2HealthEngine } from '../../core/m2_health_engine_v1.js';
import { renderLegacyHoldingZones } from './m2_holding_zones_legacy_cards.js';

const TARGET_BANK={富邦:900000,永豐:500000};
const STOCK_CAP={core:500000,growth:300000,defensive:300000,income:200000,speculative:30000};
const CAP_EXCEPTION={NVDA:700000,TSM:700000,SMH:700000,GOOG:700000};
const BUCKET_COLOR={'長期穩定現金流':'#2563eb','合理投資型':'#0f766e','積極單':'#f97316','短期投機單':'#7c3aed','其他':'#94a3b8'};
const MODULE_META={summary:['1. Summary Dashboard','資金水位 / 配置 / 健康 / 預計出場'],zones:['2. Holding Zones','到期專區 / 預計提前到期 / Danger / Watch / Healthy'],planning:['3. Maturity Cashflow','Planner A/B/C/D/E0：到期資金流與佈局重建'],market:['4. Market FCN Analysis','市場單分析與推薦，先做容量與配置判斷，後續接 M8'],management:['5. FCN / Stock Management','完整 FCN 查詢 + 股票風險分析'],pool:['6. Pool Manual Ops','手動建新單 / 編輯 / 複製 / Soft Delete / 匯出']};
let runtime=null, plannerRows=[], poolMap={}, currentModule='summary', stockCapacityRowsData=[], marketHistory=[], m8Surface=null;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const fmt=(v,d=0)=>n(v).toLocaleString('en-US',{maximumFractionDigits:d});
const pct=(v,b,d=1)=>b?fmt(v/b*100,d):'0';
const sum=list=>list.reduce((s,x)=>s+n(x.amt),0);
function bucket(x){const r=n(x.rate),t=n(x.tenor);if(t<=6&&r>20.99)return'短期投機單';if(r>=21&&r<=25)return'積極單';if(r>=18&&r<=20.99)return'合理投資型';if(r>=12&&r<=17.99)return'長期穩定現金流';return'其他'}
function kpi(k,v,d,a,extra=''){return `<div class="kpi" style="--accent:${a}"><div class="kpi-label">${k}</div><div class="kpi-value">${v}</div><div class="kpi-sub">${d}</div>${extra}</div>`}
function flowCard(k,v,d,a){return `<div class="flow-card" style="--accent:${a}"><div class="flow-label">${k}</div><div class="flow-value">${v}</div><div class="flow-sub">${d}</div></div>`}
function metricBlock(t,m,s,a){return `<div class="mini-metric" style="--accent:${a}"><div class="metric-title">${t}</div><div class="metric-main">${m}</div><div class="metric-sub">${s}</div></div>`}
function listCard(title,body,cls=''){return `<div class="list-card ${cls}"><b>${title}</b><br>${body}</div>`}
function conic(parts,total){let cur=0;return parts.map(p=>{const deg=total?p.amt/total*360:0;const s=`${BUCKET_COLOR[p.k]||'#ddd'} ${cur}deg ${cur+deg}deg`;cur+=deg;return s}).join(',')}
function miniBar(rows,total){return `<div class="mini-stack">${rows.map(r=>`<div><div class="mini-line"><span style="--bar:${r.color};width:${Math.min(100,total?r.value/total*100:0)}%"></span></div><span class="kpi-chip">${r.label} ${total?fmt(r.value/total*100,0):0}%</span></div>`).join('')}</div>`}
function dateValue(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d}
function entryDateRaw(f){return f.entry_date||f.create_date||f.trade_date||f.start_date||f.date||f.created_at||f.issue_date||null}
function daysSinceEntry(f){const d=dateValue(entryDateRaw(f));if(!d)return null;return Math.floor((Date.now()-d.getTime())/86400000)}
function stockRatio(s){const cur=n(s.price_now??s.current_price??s.spot??s.now,NaN);const ent=n(s.entry_price??s.entry??s.start_price,NaN);return Number.isFinite(cur)&&Number.isFinite(ent)&&ent>0?cur/ent:null}
function worstEntryRatio(f){const ratios=(f.stocks||[]).map(stockRatio).filter(x=>x!==null);if(!ratios.length)return null;return Math.min(...ratios)}
function isEarlyExitCandidate(f){const d=daysSinceEntry(f);const r=worstEntryRatio(f);return d!==null&&d>=27&&r!==null&&r>1}
function productType(f){return String(f.type||f.fcn_type||f.note_type||f.structure||f.product_type||'').toUpperCase().includes('AKI')?'AKI':'EKI'}
function stockNow(s){return n(s.price_now??s.current_price??s.spot??s.now,NaN)}
function stockKI(s){return n(s.ki_price??s.ki??s.knock_in_price??s.lower_barrier_price??s.barrier_price,NaN)}
function stockStrike(s){return n(s.strike_price??s.strike??s.execution_price??s.exec_price,NaN)}
function terminalBelowKI(s){const cur=stockNow(s),ki=stockKI(s);return Number.isFinite(cur)&&Number.isFinite(ki)&&ki>0?cur<ki:null}
function terminalBelowStrike(s){const cur=stockNow(s),strike=stockStrike(s);return Number.isFinite(cur)&&Number.isFinite(strike)&&strike>0?cur<strike:null}
function everBarrierBreached(s){const v=s.period_barrier_breached??s.barrier_breached??s.ki_breached??s.has_knock_in??s.knock_in_event??s.touched_ki; if(v===true||v==='true'||v==='Y'||v==='yes'||v===1)return true;if(v===false||v==='false'||v==='N'||v==='no'||v===0)return false;return null}
function projectedMaturityDate(f){const e=dateValue(entryDateRaw(f));const months=n(f.period??f.tenor??f.tenor_months,NaN);if(!e||!Number.isFinite(months))return null;const d=new Date(e);d.setMonth(d.getMonth()+months);d.setDate(d.getDate()+7);return d.toISOString().slice(0,10)}
function hasReachedProjectedMaturity(f){const p=projectedMaturityDate(f);const d=dateValue(p);return d?Date.now()>=d.getTime():false}
function maturityPayoffState(f){const type=productType(f),projected=projectedMaturityDate(f);if(!hasReachedProjectedMaturity(f)){return{maturity_state:'maturity_observe',maturity_reason:`尚未進入 entry + period + 7 days 的實際滿期結算日（${projected||'日期不足'}），列為預計滿期 / 觀察。`,maturity_type_rule:type,period_barrier_breached:null,terminal_barrier_breached:null,terminal_all_above_strike:false,terminal_any_below_strike:false,projected_maturity_date:projected}}
const stocks=f.stocks||[];const terminal=stocks.map(s=>({belowKI:terminalBelowKI(s),belowStrike:terminalBelowStrike(s),breached:everBarrierBreached(s)}));const anyBelowKI=terminal.some(x=>x.belowKI===true);const anyBelowStrike=terminal.some(x=>x.belowStrike===true);const allAboveStrike=terminal.length&&terminal.every(x=>x.belowStrike===false);const anyDataMissing=terminal.some(x=>x.belowKI===null||x.belowStrike===null||(type==='AKI'&&x.breached===null));let state='maturity_observe',reason='已進入實際滿期結算日，但資料不足；先列入預計滿期 / 觀察。';if(type==='EKI'){if(anyBelowKI){state='stock_delivery_risk';reason='EKI：滿期時任一股票破下限價，列為接股可能。';}else if(terminal.length&&!terminal.some(x=>x.belowKI===null)){state='safe_maturity';reason='EKI：滿期時至少一支 / 全部可判定未破下限價，列為滿期安全。';}}
else{const anyBreached=terminal.some(x=>x.breached===true);const noneBreached=terminal.length&&terminal.every(x=>x.breached===false);if(anyBelowKI){state='stock_delivery_risk';reason='AKI：期末任一股票破下限價，列為接股可能。';}else if(anyBreached&&anyBelowStrike){state='stock_delivery_risk';reason='AKI：期間曾破下限價，且期末任一股票低於執行價，列為接股可能。';}else if(noneBreached&&!anyBelowKI&&!anyDataMissing){state='safe_maturity';reason='AKI：期間未破下限價，且期末未破下限價，列為滿期安全。';}else if(anyBreached&&allAboveStrike){state='safe_maturity';reason='AKI：期間曾破下限價，但期末每一隻股票都高於執行價，列為滿期安全。';}}
return{maturity_state:state,maturity_reason:reason,maturity_type_rule:type,period_barrier_breached:type==='AKI'?terminal.some(x=>x.breached===true):null,terminal_barrier_breached:anyBelowKI,terminal_all_above_strike:!!allAboveStrike,terminal_any_below_strike:anyBelowStrike,projected_maturity_date:projected}}
function getGroups(){const active=plannerRows,base=active.filter(x=>x.planner_tag==='Planning Base'),ready=active.filter(x=>x.planner_tag==='Early Exit Ready'),maturity=active.filter(x=>x.planner_tag==='30D Maturity'),candidate=active.filter(x=>x.planner_tag==='Early Exit Candidate'),cash=[...ready,...maturity,...candidate];return{active,base,ready,maturity,candidate,cash,hard:[...ready,...maturity]}}
function buildPlannerRows(fcns){plannerRows=fcns.map(f=>{const d=f.maturity?.days_to_maturity??9999;let tag='Planning Base';const ratio=worstEntryRatio(f);const days=daysSinceEntry(f);const payoff=maturityPayoffState(f);if(f.early_exit_ready)tag='Early Exit Ready';else if(d<=30)tag='30D Maturity';else if(isEarlyExitCandidate(f))tag='Early Exit Candidate';return{...f,...payoff,planner_tag:tag,excluded:tag!=='Planning Base',early_exit_candidate_rule:'entry+27_and_worst_of_over_100pct_entry',early_exit_candidate_days_since_entry:days,early_exit_candidate_worst_entry_ratio:ratio,early_exit_candidate_worst_entry_pct:ratio===null?null:ratio*100}})}
function buildStockCapacityRows(){const stockMap={};plannerRows.forEach(f=>(f.basket||[]).forEach(s=>{if(!stockMap[s])stockMap[s]={symbol:s,active:0,release:0,base:0,count:0,danger:0,watch:0};stockMap[s].active+=n(f.amt);stockMap[s].count++;if(f.excluded)stockMap[s].release+=n(f.amt);else stockMap[s].base+=n(f.amt);const st=(f.stocks||[]).find(x=>x.symbol===s);if(st?.stock_health==='danger')stockMap[s].danger++;if(st?.stock_health==='watch')stockMap[s].watch++}));stockCapacityRowsData=Object.values(stockMap).map(r=>{const meta=poolMap[r.symbol]||{},category=meta.category||'growth',max=CAP_EXCEPTION[r.symbol]||STOCK_CAP[category]||300000,staticRemain=Math.max(0,max-r.active),dynamic=Math.max(0,max-r.base);let light='GREEN',comment='可正常布局';if(r.danger>0){light='RED';comment='有 danger 紀錄，先處理風險'}else if(dynamic<=0){light='RED';comment='超過上限'}else if(dynamic/max<0.2||r.watch>0){light='YELLOW';comment='接近滿載或有 watch'}return{...r,category,max,staticRemain,dynamic,light,comment}}).sort((a,b)=>a.light.localeCompare(b.light)||b.dynamic-a.dynamic)}
function allocParts(list){const targets={'長期穩定現金流':40,'合理投資型':30,'積極單':20,'短期投機單':10,'其他':0};return Object.keys(targets).map(k=>({k,target:targets[k],amt:sum(list.filter(x=>bucket(x)===k))}))}
function compactFCN(f){return `<div class="compact-fcn"><div><div class="compact-main">${f.fcn_id}</div><div class="compact-sub">${(f.basket||[]).join(' / ')}｜Worst ${f.worst_of||'-'}</div></div><div class="compact-amt">USD ${fmt(f.amt)}</div><div><span class="pill ${f.fcn_health==='danger'?'pill-bad':f.fcn_health==='watch'?'pill-warn':'pill-good'}">${f.fcn_health||'-'}</span></div><button class="detail-toggle" type="button">明細</button><div class="fcn-more">Bank: ${f.tw_bank||''}｜Rate ${fmt(f.rate,2)}%｜Tenor ${f.tenor||''}M｜Tag ${f.planner_tag}<br>Decision: ${f.decision_label||''}<br>Days to maturity: ${f.maturity?.days_to_maturity??'-'}｜Early Exit ${f.early_exit_remark_count??0}/${f.early_exit_total_count??0}</div></div>`}
function bindDetailToggles(){document.querySelectorAll('.detail-toggle').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.compact-fcn')?.classList.toggle('open')))}
function renderTopDashboard(){const g=getGroups(),parts=allocParts(g.active),total=sum(g.active)||1,bankF=sum(g.active.filter(x=>(x.tw_bank||'').includes('富邦'))),bankS=sum(g.active.filter(x=>(x.tw_bank||'').includes('永豐'))),cashTotal=sum(g.cash)||1;topDashboard.innerHTML=[kpi('FCN 資金水位',`USD ${fmt(sum(g.active))}`,`${g.active.length} 檔｜富邦 ${fmt(bankF)} / 永豐 ${fmt(bankS)}`,'#2563eb',miniBar([{label:'富邦',value:bankF,color:'#2563eb'},{label:'永豐',value:bankS,color:'#0f766e'}],sum(g.active))),kpi('本月預計出場',`USD ${fmt(sum(g.cash))}`,`到期 ${fmt(sum(g.maturity))}｜提前 ${fmt(sum(g.ready))}｜候選 ${fmt(sum(g.candidate))}`,'#f97316',miniBar([{label:'到期',value:sum(g.maturity),color:'#dc2626'},{label:'提前',value:sum(g.ready),color:'#0f766e'},{label:'候選',value:sum(g.candidate),color:'#f97316'}],cashTotal)),kpi('健康狀態',`${runtime.danger.length+runtime.watch.length} 需看`,`Danger ${runtime.danger.length}｜Watch ${runtime.watch.length}｜Healthy ${runtime.healthy.length}`,'#dc2626',miniBar([{label:'Danger',value:runtime.danger.length,color:'#dc2626'},{label:'Watch',value:runtime.watch.length,color:'#f97316'},{label:'Healthy',value:runtime.healthy.length,color:'#0f766e'}],Math.max(1,runtime.total))),kpi('Planning Base',`USD ${fmt(sum(g.base))}`,`${g.base.length} 檔｜扣除本月出場後母體`,'#0f766e'),kpi('配置主軸',parts.map(p=>`${p.k.slice(0,2)} ${fmt(p.amt/total*100,0)}%`).join('｜'),'目前 active 配置粗覽','#7c3aed',miniBar(parts.map(p=>({label:p.k.slice(0,2),value:p.amt,color:BUCKET_COLOR[p.k]})),total)),kpi('系統模式','Read-only','不改舊 M2 / Planner，不寫回資料','#64748b')].join('')}
function setModule(m){currentModule=m;document.querySelectorAll('.menu-btn').forEach(b=>b.classList.toggle('active',b.dataset.module===m));document.getElementById('m2HoldingZonesSubnav')?.classList.toggle('show',m==='zones');document.getElementById('m2MaturityCashflowSubnav')?.classList.toggle('show',m==='planning');const meta=MODULE_META[m];activeTitle.textContent=meta[0];activeSub.textContent=meta[1];bottomTitle.textContent=`${meta[0]}｜大型資訊查詢區`;bottomSub.textContent=meta[1];renderCurrentModule()}
function renderCurrentModule(){if(!runtime)return;({summary:renderSummary,zones:renderZones,planning:renderPlanning,market:renderMarket,management:renderManagement,pool:renderPool}[currentModule]||renderSummary)();bindDetailToggles();bindFilters()}
function renderSummary(){const g=getGroups();rightDetail.innerHTML=`<div class="flow-panel">${flowCard('Active',`${g.active.length} / USD ${fmt(sum(g.active))}`,'目前持倉','#2563eb')}${flowCard('Expected Exit',`${g.cash.length} / USD ${fmt(sum(g.cash))}`,'本月預計出場','#f97316')}${flowCard('Planning Base',`${g.base.length} / USD ${fmt(sum(g.base))}`,'真正分析母體','#0f766e')}${flowCard('Risk',`${runtime.danger.length+runtime.watch.length}`,'Danger + Watch','#dc2626')}</div>`;rightInsight.innerHTML=`<div class="decision-note">M2 Summary 要一眼看完：現在有多少 FCN、健康度如何、本月預計釋放多少資金，以及釋放來源。下一步配置必須以 Planning Base 為母體，不是拿 Active 全部直接分析。</div>`;bottomQuery.innerHTML=`<div class="grid-3"><div class="panel"><h3>本月出場來源</h3>${listCard('30D Maturity',`${g.maturity.length} 檔｜USD ${fmt(sum(g.maturity))}`)}${listCard('Early Exit Ready',`${g.ready.length} 檔｜USD ${fmt(sum(g.ready))}`)}${listCard('Early Exit Candidate',`${g.candidate.length} 檔｜USD ${fmt(sum(g.candidate))}`)}</div><div class="panel"><h3>銀行資金水位</h3>${Object.keys(TARGET_BANK).map(b=>{const a=sum(g.active.filter(x=>(x.tw_bank||'').includes(b)));return listCard(b,`Active USD ${fmt(a)}｜Target USD ${fmt(TARGET_BANK[b])}｜Util ${pct(a,TARGET_BANK[b])}%`)}).join('')}</div><div class="panel"><h3>健康摘要</h3>${listCard('到期專區',`${runtime.maturity_zone.length} 檔`)}${listCard('Danger / Watch',`${runtime.danger.length} / ${runtime.watch.length} 檔`)}${listCard('Healthy',`${runtime.healthy.length} 檔`)}</div></div>`}
function renderZones(){renderLegacyHoldingZones({runtime,groups:getGroups(),rightDetail,rightInsight,bottomQuery})}
function renderBrokerBlock(){const g=getGroups();return `<div class="broker-grid">${Object.keys(TARGET_BANK).map(b=>{const target=TARGET_BANK[b],cur=g.active.filter(x=>(x.tw_bank||'').includes(b)),base=g.base.filter(x=>(x.tw_bank||'').includes(b)),exit=g.cash.filter(x=>(x.tw_bank||'').includes(b)),activeAmt=sum(cur),baseAmt=sum(base),exitAmt=sum(exit),future=Math.max(0,target-baseAmt);return `<div class="broker-card"><div class="broker-head"><div><b>${b}</b><div class="muted">Future Available</div></div><div class="broker-avail">USD ${fmt(future)}</div></div><div class="broker-metrics">${metricBlock('出場',`${exit.length} / USD ${fmt(exitAmt)}`,`${pct(exitAmt,activeAmt)}% Active`,'#f97316')}${metricBlock('剩餘母體',`${base.length} / USD ${fmt(baseAmt)}`,`${pct(baseAmt,activeAmt)}% Active`,'#0f766e')}${metricBlock('原母體',`${cur.length} / USD ${fmt(activeAmt)}`,`${pct(activeAmt,target)}% Target`,'#2563eb')}${metricBlock('可補',`USD ${fmt(future)}`,`${pct(future,target)}% open`,'#7c3aed')}</div></div>`}).join('')}</div>`}
function renderAllocBlock(){const g=getGroups(),base=g.base,total=sum(base)||1,parts=allocParts(base);return `<div class="alloc-layout"><div class="panel"><b>Planning Base 結構</b><div class="pie" style="background:conic-gradient(${conic(parts,total)})"></div>${parts.map(p=>`<div class="legend-row"><span><i class="legend-dot" style="background:${BUCKET_COLOR[p.k]}"></i>${p.k}</span><b>${fmt(p.amt/total*100,1)}%</b></div>`).join('')}</div><div class="panel"><b>Real vs Target</b>${parts.map(p=>{const bp=p.amt/total*100,gap=bp-p.target;return `<div class="alloc-row"><div><b>${p.k}</b><div class="muted">USD ${fmt(p.amt)} / ${fmt(bp,1)}%</div><div class="bar"><span style="--bar:${BUCKET_COLOR[p.k]};width:${Math.min(100,bp)}%"></span></div></div><div><b>Target ${p.target}%</b><div class="muted">Gap ${fmt(gap,1)}%</div></div></div>`}).join('')}</div><div class="panel"><div class="interpret-box"><div class="interpret-title">Planning Logic</div>此區是 m2_planner A/B/C/D/E0 的位置，負責到期資金流與重建佈局，不應佔滿整個 M2。</div></div></div>`}

function planningDecisionBlock(){
  const g=getGroups(),hard=sum(g.hard),soft=sum(g.candidate),conservative=hard,aggressive=hard+soft*0.5;
  const base=g.base,total=sum(base)||1,parts=allocParts(base).map(p=>({...p,pct:p.amt/total*100,gap:p.amt/total*100-p.target}));
  const under=parts.filter(p=>p.gap<0).sort((a,b)=>a.gap-b.gap);
  const over=parts.filter(p=>p.gap>0).sort((a,b)=>b.gap-a.gap);
  const bankLines=Object.keys(TARGET_BANK).map(b=>{const baseAmt=sum(g.base.filter(x=>(x.tw_bank||'').includes(b))),hardAmt=sum(g.hard.filter(x=>(x.tw_bank||'').includes(b))),candidateAmt=sum(g.candidate.filter(x=>(x.tw_bank||'').includes(b))),available=Math.max(0,TARGET_BANK[b]-baseAmt);return{bank:b,baseAmt,hardAmt,candidateAmt,available,util:TARGET_BANK[b]?baseAmt/TARGET_BANK[b]*100:0};});
  const bankBest=bankLines.slice().sort((a,b)=>b.available-a.available)[0];
  const first=under[0]?.k||'暫無明顯缺口';
  const second=under[1]?.k||'視市場單品質';
  return `<div class="planner-decision" id="planner-decision"><div class="planner-decision-title">Planner Decision｜本月資金結論</div><div class="planner-decision-grid"><div><label>保守可用</label><b>USD ${fmt(conservative)}</b><span>只計 Hard Release</span></div><div><label>積極可用</label><b>USD ${fmt(aggressive)}</b><span>Hard + 50% Candidate</span></div><div><label>優先銀行</label><b>${bankBest?.bank||'-'}</b><span>釋放後可用 USD ${fmt(bankBest?.available||0)}</span></div><div><label>優先補類別</label><b>${first}</b><span>第二順位：${second}</span></div></div><div class="planner-one-line">操作建議：先以 Hard Release 作保守資金池，Candidate 不全數視為現金；新單優先補「${first}」，若市場票息不足，再用「${second}」候補。</div>${over.length?`<div class="planner-warn">暫停或降權：${over.slice(0,2).map(p=>`${p.k} +${fmt(p.gap,1)}%`).join('｜')}</div>`:''}</div>`;
}
function renderCashInBlock(){
  const g=getGroups();
  return `<div class="cashflow-section" id="planner-cash-in"><div class="section-head"><div><h3>A. 本月可用資金總覽</h3><p>Hard Release 是保守可用資金，Soft Candidate 先列觀察，不全數當現金。</p></div></div><div class="flow-panel">${flowCard('確定釋放',`USD ${fmt(sum(g.hard))}`,`${g.hard.length} 檔｜30D + Ready`,'#dc2626')}${flowCard('可能釋放',`USD ${fmt(sum(g.candidate))}`,`${g.candidate.length} 檔｜Candidate`,'#f97316')}${flowCard('保守可用',`USD ${fmt(sum(g.hard))}`,'只計確定釋放','#0f766e')}${flowCard('積極可用',`USD ${fmt(sum(g.hard)+sum(g.candidate)*0.5)}`,'Hard + 50% Candidate','#7c3aed')}</div></div>`;
}
function renderBankCapacityBlock(){
  const g=getGroups();
  return `<div class="cashflow-section" id="planner-bank-capacity"><div class="section-head"><div><h3>B. 銀行資金水位</h3><p>釋放後看哪一家銀行有空間承接新單。</p></div></div><div class="broker-grid">${Object.keys(TARGET_BANK).map(b=>{const target=TARGET_BANK[b],active=sum(g.active.filter(x=>(x.tw_bank||'').includes(b))),hard=sum(g.hard.filter(x=>(x.tw_bank||'').includes(b))),candidate=sum(g.candidate.filter(x=>(x.tw_bank||'').includes(b))),base=sum(g.base.filter(x=>(x.tw_bank||'').includes(b))),available=Math.max(0,target-base);let msg=available>target*0.25?'有空間，可優先承接新單':available>target*0.1?'可小額承接，需控單':'偏滿，優先不補或只補小額';return `<div class="broker-card"><div class="broker-head"><div><b>${b}</b><div class="muted">${msg}</div></div><div class="broker-avail">USD ${fmt(available)}</div></div><div class="broker-metrics">${metricBlock('Active',`USD ${fmt(active)}`,`${pct(active,target)}% target`,'#2563eb')}${metricBlock('Expected Release',`USD ${fmt(hard)}`,`Candidate USD ${fmt(candidate)}`,'#f97316')}${metricBlock('Planning Base',`USD ${fmt(base)}`,`${pct(base,target)}% target`,'#0f766e')}${metricBlock('Available',`USD ${fmt(available)}`,`${pct(available,target)}% open`,'#7c3aed')}</div></div>`}).join('')}</div></div>`;
}
function renderReleaseDetailsBlock(){
  const g=getGroups();
  return `<div class="cashflow-section" id="planner-fcn-detail"><div class="section-head"><div><h3>C. FCN 明細</h3><p>左側快速導航會連到這三段：Hard Release / Soft Candidate / Planning Base。</p></div></div><div class="cash-grid"><div class="cash-card" id="planner-hard-release"><div class="cash-title">Hard Release｜確定釋放</div>${g.hard.map(compactFCN).join('')||'<div class="muted">none</div>'}</div><div class="cash-card" id="planner-soft-candidate"><div class="cash-title">Soft Candidate｜觀察釋放</div>${g.candidate.map(compactFCN).join('')||'<div class="muted">none</div>'}</div><div class="cash-card" id="planner-planning-base"><div class="cash-title">Planning Base｜扣除後母體</div>${g.base.slice(0,12).map(compactFCN).join('')}</div></div></div>`;
}
function renderPlanningBaseBlock(){
  return `<div class="cashflow-section" id="planner-allocation"><div class="section-head"><div><h3>D. 扣除後 Planning Base 配置</h3><p>扣除本月確定 / 可能出場後，檢查四大類距離目標配置。</p></div></div>${renderAllocBlock()}</div>`;
}
function bindMaturitySubnav(){
  const nav=document.getElementById('m2MaturityCashflowSubnav');
  if(!nav||nav.dataset.bound==='1')return;
  nav.dataset.bound='1';
  nav.addEventListener('click',ev=>{
    const btn=ev.target.closest('[data-planner-nav],[data-planner-action]');
    if(!btn)return;
    ev.preventDefault();
    const key=btn.dataset.plannerNav;
    const action=btn.dataset.plannerAction;
    setModule('planning');
    setTimeout(()=>{
      if(action==='toggle-dashboard'){
        document.getElementById('topDashboard')?.classList.toggle('m2-dashboard-open');
        return;
      }
      const map={cash:'planner-cash-in',bank:'planner-bank-capacity',detail:'planner-fcn-detail',hard:'planner-hard-release',soft:'planner-soft-candidate',base:'planner-planning-base',alloc:'planner-allocation',decision:'planner-decision'};
      const el=document.getElementById(map[key]||'bottomQuery');
      el?.scrollIntoView({behavior:'smooth',block:'start'});
    },220);
  });
}

function renderPlanning(){const g=getGroups();rightDetail.innerHTML=`<div class="flow-panel">${flowCard('本月可用',`USD ${fmt(sum(g.hard))}`,'保守：Hard Release','#0f766e')}${flowCard('積極可用',`USD ${fmt(sum(g.hard)+sum(g.candidate)*0.5)}`,'Hard + 50% Candidate','#7c3aed')}${flowCard('觀察釋放',`USD ${fmt(sum(g.candidate))}`,`${g.candidate.length} 檔 candidate`,'#f97316')}${flowCard('Planning Base',`USD ${fmt(sum(g.base))}`,`${g.base.length} 檔扣除後母體`,'#2563eb')}</div>`;rightInsight.innerHTML=`<div class="decision-note">Maturity Cashflow 只回答三件事：本月多少錢會回來、哪家銀行有空間、扣除後應該補哪一類 FCN。Candidate 先列觀察，不全數視為現金。</div>`;bottomQuery.innerHTML=`${planningDecisionBlock()}${renderCashInBlock()}${renderBankCapacityBlock()}${renderPlanningBaseBlock()}${renderReleaseDetailsBlock()}`;bindMaturitySubnav()}

function normalizeBasket(symbols=[]){return [...new Set((symbols||[]).map(s=>String(s||'').trim().toUpperCase()).filter(Boolean).map(s=>s==='GOOGL'?'GOOG':s))].sort().join('+')}
function orderFromInput(){return{product_id:'NEW_CHECK',source:'manual',symbols:(document.getElementById('inqBasket')?.value||'').toUpperCase().split(/[,+/\s]+/).map(x=>x.trim()).filter(Boolean),coupon_pct:n(document.getElementById('inqCoupon')?.value,0),tenor_month:n(document.getElementById('inqTenor')?.value,0),strike_pct:n(document.getElementById('inqStrike')?.value,0),ki_pct:n(document.getElementById('inqKI')?.value,NaN),barrier_type:document.getElementById('inqType')?.value||'EKI',memory_type:document.getElementById('inqMemory')?.value||'daily',source_bank:document.getElementById('inqBank')?.value||'富邦',amt:n(document.getElementById('inqAmount')?.value,0)}}
function classifyMarketTemplate(o){const syms=(o.symbols||[]).map(s=>String(s).toUpperCase());const c=n(o.coupon_pct),tenor=n(o.tenor_month),strike=n(o.strike_pct),ki=n(o.ki_pct,NaN);const has=x=>syms.includes(x);const hasAny=arr=>arr.some(has);if(c>=25||tenor<=3&&c>=21)return{code:'D',name:'高票息極短投機單',big:'D_SPECULATIVE_MOMENTUM'};if(hasAny(['COIN','ALAB','CRDO','SOFI','TSLA','PLTR','LITE'])&&(c>=21||strike>60||ki>50))return{code:'C',name:'積極投機高利率單',big:'D_SPECULATIVE_MOMENTUM'};if(hasAny(['MU','AMD','MRVL','ARM','INTC'])&&c>=17&&c<=23&&tenor<=9&&strike<=65&&(Number.isNaN(ki)||ki<=60))return{code:'B',name:'理性型投機單',big:'B_MEMORY_SEMI_TACTICAL'};if(hasAny(['AAPL','GOOG','MSFT','LQD','QQQ','SMH'])&&c<=16)return{code:'E',name:'防守 / 降速器單',big:'E_DEFENSIVE_STABILIZER'};if(hasAny(['NVDA','TSM','AVGO','MSFT','GOOG','AMZN','AMAT','ORCL'])&&c>=12&&c<=19)return{code:'A',name:'大型股穩定收息',big:'A_AI_CORE_INSTITUTIONAL'};return{code:'F',name:'Outlier / 需人工確認',big:'F_OTHERS_M7_BASKET_DRIVEN'}}
function getSurfaceTemplates(){return m8Surface?.templates||{}}
function matchM8Template(o){const key=normalizeBasket(o.symbols),cls=classifyMarketTemplate(o),templates=getSurfaceTemplates(),big=templates[cls.big];let small=null;const smallPools=[m8Surface?.small_templates,m8Surface?.sub_templates,m8Surface?.smallTemplates].filter(Boolean);for(const pool of smallPools){for(const [k,v] of Object.entries(pool||{})){if(normalizeBasket(String(k).split(/[+/, ]+/))===key||normalizeBasket(v.symbols||[])===key){small={id:k,...v};break}}if(small)break}const final=n(small?.avg_final_fair_rate??small?.final_fair_rate??big?.avg_final_fair_rate,NaN),market=n(o.coupon_pct,NaN),gap=Number.isFinite(final)&&Number.isFinite(market)?market-final:null;let rateDecision='M8 Template 待接';if(gap!==null){if(gap>1)rateDecision='利率偏甜，但需看風險';else if(gap<-1)rateDecision='利率偏低，不值得';else rateDecision='利率合理';}let coverage='Missing';if(small&&gap!==null&&Math.abs(gap)<=1)coverage='Covered';else if(small)coverage=Math.abs(gap||0)>2?'Broken':'Weak';else if(big)coverage=gap!==null&&Math.abs(gap)>2?'Weak':'Big Template Fallback';return{key,classification:cls,big_template:cls.big,big,small_template:small?.id||null,final_fair:final,old_fair:n(big?.avg_old_fair_rate,NaN),new_fair:n(big?.avg_new_fair_rate,NaN),beta:n(big?.avg_beta,NaN),market_coupon:market,gap,coverage,rateDecision}}
function stockInvestabilityCheck(o){const amt=n(o.amt,0);const rows=(o.symbols||[]).map(s=>{const row=stockCapacityRowsData.find(x=>x.symbol===String(s).toUpperCase());if(!row)return{symbol:s,decision:'需確認',light:'UNKNOWN',comment:'不在 M2 capacity 表'};const after=row.dynamic-amt;let decision='可投入',light='GREEN';if(row.light==='RED'||after<0){decision='拒絕 / 超容量';light='RED'}else if(row.light==='YELLOW'||after<row.max*0.2){decision='小額';light='YELLOW'}return{symbol:s,decision,light,active:row.active,dynamic:row.dynamic,after,comment:row.comment}});const red=rows.filter(r=>r.light==='RED').length,yellow=rows.filter(r=>r.light==='YELLOW').length;return{rows,decision:red?'拒絕':yellow?'小額':'可投入'}}
function evaluateMarketOrder(o){const m8=matchM8Template(o),stock=stockInvestabilityCheck(o),bucket=classifyMarketTemplate(o);let final='可研究';if(stock.decision==='拒絕'||bucket.code==='F'||bucket.code==='D')final='拒絕 / 極小額';else if(stock.decision==='小額'||['B','C'].includes(bucket.code))final='小額可研究';if(m8.gap!==null&&m8.gap<-1)final='不值得';return{order:o,bucket,m8,stock,final}}
function groupMarketHistory(history){const map={};(history||[]).forEach(o=>{const k=normalizeBasket(o.symbols);if(!map[k])map[k]=[];map[k].push(o)});return Object.entries(map).map(([key,rows])=>({key,rows,count:rows.length,avgCoupon:rows.reduce((s,x)=>s+n(x.coupon_pct),0)/rows.length,avgStrike:rows.reduce((s,x)=>s+n(x.strike_pct),0)/rows.length,avgKI:rows.reduce((s,x)=>s+n(x.ki_pct,0),0)/rows.length,avgTenor:rows.reduce((s,x)=>s+n(x.tenor_month),0)/rows.length,cls:classifyMarketTemplate(rows[0])})).sort((a,b)=>b.count-a.count||b.avgCoupon-a.avgCoupon)}
function batchTrend(){const rows=marketHistory||[];const latest=rows.map(r=>r.generated_at).sort().slice(-1)[0];const today=rows.filter(r=>r.generated_at===latest);const evals=today.map(evaluateMarketOrder);const dist={};evals.forEach(x=>dist[x.bucket.name]=(dist[x.bucket.name]||0)+1);const mainstream=groupMarketHistory(today).filter(g=>g.count>=2).slice(0,8);const stockFreq={};today.forEach(o=>(o.symbols||[]).forEach(s=>{s=String(s).toUpperCase();if(!stockFreq[s])stockFreq[s]={symbol:s,count:0,coupon:0};stockFreq[s].count++;stockFreq[s].coupon+=n(o.coupon_pct)}));const stocks=Object.values(stockFreq).map(x=>({...x,avgCoupon:x.coupon/x.count})).sort((a,b)=>b.count-a.count||b.avgCoupon-a.avgCoupon);return{latest,today,evals,dist,mainstream,stocks}}
function renderMarketSummaryCards(bt){const total=bt.evals.length||1;const main=Object.entries(bt.dist).sort((a,b)=>b[1]-a[1])[0];return `<div class="flow-panel">${flowCard('Today Orders',bt.evals.length,`日期 ${bt.latest||'-'}`,'#2563eb')}${flowCard('主流模板',main?main[0]:'-',main?`${main[1]} 張 / ${fmt(main[1]/total*100,0)}%`:'無資料','#0f766e')}${flowCard('Mainstream Basket',bt.mainstream.length,`重複 basket >=2`,'#f97316')}${flowCard('M8 Coverage',`${bt.evals.filter(x=>x.m8.coverage==='Covered').length}/${bt.evals.length}`,`Covered / today`,'#7c3aed')}</div>`}
function renderM8UpdateSuggestions(bt){const items=bt.mainstream.map(g=>{const m=matchM8Template(g.rows[0]);let suggestion='維持觀察';if(!m.small_template&&g.count>=2)suggestion=`建議新增小模板 ${g.key}`;if(m.gap!==null&&Math.abs(m.gap)>2)suggestion=`建議修正 ${m.big_template} premium / β`;return{g,m,suggestion}});return `<div class="panel" id="market-m8-coverage"><h3>D. M8 Template Coverage / Update Suggestions</h3>${items.length?items.map(x=>`<div class="list-card"><b>${x.g.key}</b>｜${x.g.count} 張｜Avg Coupon ${fmt(x.g.avgCoupon,2)}%｜${x.g.cls.name}<br>M8：${x.m.big_template}｜Small ${x.m.small_template||'Missing'}｜Coverage ${x.m.coverage}｜Gap ${x.m.gap===null?'-':fmt(x.m.gap,2)+'%'}<br><b>建議：</b>${x.suggestion}</div>`).join(''):'<div class="muted">目前沒有重複主流 basket。</div>'}</div>`}
function renderBatchMarketAnalysis(){const bt=batchTrend();return `<div id="market-batch">${renderMarketSummaryCards(bt)}<div class="grid-2" style="margin-top:12px"><div class="panel" id="market-template-trend"><h3>C. Market Mainstream Template</h3>${bt.mainstream.length?bt.mainstream.map(g=>`<div class="list-card"><b>${g.key}</b><br>${g.count} 張｜Coupon ${fmt(g.avgCoupon,2)}%｜Strike ${fmt(g.avgStrike,1)}｜KI ${fmt(g.avgKI,1)}｜Tenor ${fmt(g.avgTenor,1)}M<br>${g.cls.name}：${g.cls.code}</div>`).join(''):'<div class="muted">尚未形成重複主流 basket。</div>'}</div><div class="panel"><h3>Stock Trend｜個股出現頻率</h3>${bt.stocks.slice(0,12).map(s=>`<div class="legend-row"><span><b>${s.symbol}</b></span><b>${s.count} 次｜Avg ${fmt(s.avgCoupon,1)}%</b></div>`).join('')}</div></div>${renderM8UpdateSuggestions(bt)}<div class="panel" style="margin-top:12px"><h3>今日單分析</h3><div class="table-wrap"><table><thead><tr><th>ID</th><th>Basket</th><th>Coupon</th><th>Tenor</th><th>Strike/KI</th><th>Template</th><th>M8</th><th>Gap</th><th>Stocks</th><th>Decision</th></tr></thead><tbody>${bt.evals.map(x=>`<tr><td><b>${x.order.product_id||'-'}</b><br>${x.order.source||''}</td><td>${normalizeBasket(x.order.symbols)}</td><td>${fmt(x.order.coupon_pct,2)}%</td><td>${x.order.tenor_month}M</td><td>${fmt(x.order.strike_pct,1)} / ${Number.isFinite(n(x.order.ki_pct,NaN))?fmt(x.order.ki_pct,1):'-'}</td><td>${x.bucket.code}｜${x.bucket.name}</td><td>${x.m8.big_template}<br>${x.m8.small_template||'small missing'}</td><td>${x.m8.gap===null?'-':fmt(x.m8.gap,2)+'%'}</td><td>${x.stock.decision}</td><td><b>${x.final}</b></td></tr>`).join('')}</tbody></table></div></div></div>`}
function evaluateInquiry(){const result=evaluateMarketOrder(orderFromInput());inqResult.innerHTML=`<div class="decision-note"><b>Final｜${result.final}</b><br>Bucket：${result.bucket.code}｜${result.bucket.name}<br>M8：${result.m8.big_template} / ${result.m8.small_template||'small missing'}｜Final Fair ${Number.isFinite(result.m8.final_fair)?fmt(result.m8.final_fair,2)+'%':'待接'}｜Market ${fmt(result.m8.market_coupon,2)}%｜Gap ${result.m8.gap===null?'-':fmt(result.m8.gap,2)+'%'}｜${result.m8.rateDecision}<br>Stocks：${result.stock.decision}</div><div class="table-wrap"><table><thead><tr><th>Stock</th><th>Dynamic</th><th>After</th><th>Light</th><th>Comment</th></tr></thead><tbody>${result.stock.rows.map(x=>`<tr class="${x.light==='RED'?'row-bad':x.light==='YELLOW'?'row-warn':'row-good'}"><td><b>${x.symbol}</b></td><td>${x.dynamic===undefined?'N/A':'USD '+fmt(x.dynamic)}</td><td>${x.after===undefined?'N/A':'USD '+fmt(x.after)}</td><td>${x.light}</td><td>${x.comment}</td></tr>`).join('')}</tbody></table></div>`}
const basket=(document.getElementById('inqBasket')?.value||'').toUpperCase().split(/[,+/\s]+/).map(x=>x.trim()).filter(Boolean),amt=n(document.getElementById('inqAmount')?.value,0),coupon=n(document.getElementById('inqCoupon')?.value,0),tenor=n(document.getElementById('inqTenor')?.value,12),bank=document.getElementById('inqBank')?.value||'富邦';const f={rate:coupon,tenor};const bkt=bucket(f);const stockLines=basket.map(s=>{const row=stockCapacityRowsData.find(x=>x.symbol===s);const dyn=row?row.dynamic:0;const after=dyn-amt;const light=!row?'UNKNOWN':after<0?'RED':after<row.max*0.2?'YELLOW':'GREEN';return{symbol:s,row,dyn,after,light}});const bankBase=sum(getGroups().base.filter(x=>(x.tw_bank||'').includes(bank))),bankFuture=Math.max(0,TARGET_BANK[bank]-bankBase),bankAfter=bankFuture-amt;const red=stockLines.filter(x=>x.light==='RED').length,unknown=stockLines.filter(x=>x.light==='UNKNOWN').length;let decision='可研究';let cls='pill-good';if(red||bankAfter<0){decision='不建議 / 超容量';cls='pill-bad'}else if(unknown||stockLines.some(x=>x.light==='YELLOW')){decision='小額 / 需確認';cls='pill-warn'}inqResult.innerHTML=`<div class="decision-note"><span class="pill ${cls}">${decision}</span><br>Bucket：<b>${bkt}</b>｜Bank：<b>${bank}</b>｜Amount：USD <b>${fmt(amt)}</b>｜Coupon：<b>${fmt(coupon,2)}%</b>｜Tenor：<b>${tenor}M</b><br>銀行未來可用：USD ${fmt(bankFuture)} → 下單後 USD ${fmt(bankAfter)}。${unknown?' 有標的不在 pool30 / capacity 表中，需人工確認。':''}</div><div class="table-wrap"><table><thead><tr><th>Stock</th><th>Current Dynamic</th><th>After Order</th><th>Light</th><th>Comment</th></tr></thead><tbody>${stockLines.map(x=>`<tr class="${x.light==='RED'?'row-bad':x.light==='YELLOW'?'row-warn':'row-good'}"><td><b>${x.symbol}</b></td><td>${x.row?'USD '+fmt(x.dyn):'N/A'}</td><td>${x.row?'USD '+fmt(x.after):'N/A'}</td><td><span class="pill ${x.light==='RED'?'pill-bad':x.light==='YELLOW'?'pill-warn':'pill-good'}">${x.light}</span></td><td>${x.row?x.row.comment:'未在目前 FCN / pool30 容量表'}</td></tr>`).join('')}</tbody></table></div>`}
function renderMarket(){const bt=batchTrend();rightDetail.innerHTML=renderMarketSummaryCards(bt);rightInsight.innerHTML=`<div class="decision-note">第4區 = New Market FCN Check + Batch Market FCN Analysis + M8 Template Coverage。先用 M2 Gate 判斷能不能做，再用 M8 大小模板判斷利率是否合理，最後把市場主流模板回饋給 M8 更新。</div>`;bottomQuery.innerHTML=`<div class="grid-2"><div class="panel" id="market-new-check"><h3>A. New Market FCN Check</h3><div class="table-tools"><input id="inqBasket" placeholder="Basket: NVDA,TSM,MU"><input id="inqCoupon" type="number" step="0.01" placeholder="Coupon %"><input id="inqTenor" type="number" step="1" placeholder="Tenor 月"><input id="inqStrike" type="number" step="0.01" placeholder="Strike %"><input id="inqKI" type="number" step="0.01" placeholder="KI %"><input id="inqAmount" type="number" step="1000" placeholder="Amount USD"><select id="inqType"><option>EKI</option><option>AKI</option><option>NA</option><option>DACN</option></select><select id="inqMemory"><option>daily</option><option>monthly</option></select><select id="inqBank"><option>富邦</option><option>永豐</option></select><button id="inqRun" type="button">Check</button></div><div id="inqResult" class="muted">輸入市場單後按 Check。</div></div><div class="panel"><h3>B. Batch Market FCN Analysis</h3><div class="decision-note">讀取 data/mm/market_fcn_history.json，輸出今日主流、basket 模板、M8 coverage 與更新建議。</div>${renderMarketSummaryCards(bt)}</div></div><div style="height:12px"></div>${renderBatchMarketAnalysis()}`;document.getElementById('inqRun')?.addEventListener('click',evaluateInquiry)}
function renderManagement(){rightDetail.innerHTML=`<div class="flow-panel">${flowCard('FCN Rows',plannerRows.length,'完整 FCN 查詢母體','#2563eb')}${flowCard('Stock Rows',stockCapacityRowsData.length,'股票風險 + 容量','#0f766e')}${flowCard('Danger Stocks',stockCapacityRowsData.filter(x=>x.light==='RED').length,'需優先看','#dc2626')}${flowCard('Watch Stocks',stockCapacityRowsData.filter(x=>x.light==='YELLOW').length,'接近滿載或 watch','#f97316')}</div>`;rightInsight.innerHTML=`<div class="decision-note">第5區合併 m2_planner E 與 m2 的股票風險分析。這裡是查詢與風險管理，不是手動新增修改。</div>`;bottomQuery.innerHTML=`<div class="table-tools"><input id="fcnSearch" placeholder="搜尋 FCN / Stock / Bank"><select id="fcnTagFilter"><option value="all">Planner Tag: All</option><option>Planning Base</option><option>30D Maturity</option><option>Early Exit Ready</option><option>Early Exit Candidate</option></select><select id="stockLightFilter"><option value="all">Stock Light: All</option><option>GREEN</option><option>YELLOW</option><option>RED</option></select></div><div id="managementTables"></div>`;renderManagementTables()}
function renderManagementTables(){const q=(document.getElementById('fcnSearch')?.value||'').toUpperCase(),tag=document.getElementById('fcnTagFilter')?.value||'all',light=document.getElementById('stockLightFilter')?.value||'all';const stocks=stockCapacityRowsData.filter(x=>(light==='all'||x.light===light)&&(x.symbol.includes(q)||x.category.toUpperCase().includes(q)));const fcns=plannerRows.filter(x=>(tag==='all'||x.planner_tag===tag)&&(`${x.fcn_id} ${x.tw_bank} ${(x.basket||[]).join(' ')}`.toUpperCase().includes(q)));managementTables.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Stock</th><th>Category</th><th>Max</th><th>Active</th><th>Exit Release</th><th>Planning Base</th><th>Static Rem.</th><th>Dynamic</th><th>Light</th><th>Comment</th></tr></thead><tbody>${stocks.map(x=>`<tr class="${x.light==='RED'?'row-bad':x.light==='YELLOW'?'row-warn':'row-good'}"><td><b>${x.symbol}</b></td><td>${x.category}</td><td>USD ${fmt(x.max)}</td><td>USD ${fmt(x.active)}</td><td>USD ${fmt(x.release)}</td><td>USD ${fmt(x.base)}</td><td>USD ${fmt(x.staticRemain)}</td><td>USD ${fmt(x.dynamic)}</td><td><span class="pill ${x.light==='GREEN'?'pill-good':x.light==='YELLOW'?'pill-warn':'pill-bad'}">${x.light}</span></td><td>${x.comment}</td></tr>`).join('')}</tbody></table></div><div style="height:12px"></div>${renderFCNTable(fcns)}`}
function renderFCNTable(rows=plannerRows){return `<div class="table-wrap"><table><thead><tr><th>FCN ID</th><th>Bank</th><th>Amount</th><th>Rate</th><th>Tenor</th><th>Basket</th><th>Worst-of</th><th>Health</th><th>Planner Tag</th><th>Days to Maturity</th></tr></thead><tbody>${rows.map(x=>`<tr class="${x.fcn_health==='danger'?'row-bad':x.fcn_health==='watch'?'row-warn':'row-good'}"><td><b>${x.fcn_id}</b></td><td>${x.tw_bank||''}</td><td>USD ${fmt(x.amt)}</td><td>${fmt(x.rate,2)}%</td><td>${x.tenor||''}M</td><td>${(x.basket||[]).join(' / ')}</td><td>${x.worst_of||''}</td><td>${x.maturity_state||x.decision_label||''}</td><td>${x.planner_tag}</td><td>${x.maturity?.days_to_maturity??'-'}</td></tr>`).join('')}</tbody></table></div>`}
function renderPool(){rightDetail.innerHTML=`<div class="note">第6區來源是舊 m2 / 6. FCN Pool 管理。此區未來放手動建新單、編輯、複製、Soft Delete、匯出。</div>`;rightInsight.innerHTML=`<div class="decision-note">這是後台作業區，不應混在 Summary 或 Planner。新版會先把手動鍵新單流程整理乾淨，再考慮寫回。</div>`;bottomQuery.innerHTML=`<div class="grid-3"><div class="panel"><h3>手動建新單</h3><div class="table-tools"><input placeholder="fcn_id"><input placeholder="basket"><input placeholder="amount"><input placeholder="coupon"><select><option>active</option><option>draft</option></select></div><div class="muted">待搬 m2 6.2 表單。</div></div><div class="panel"><h3>FCN 清單</h3><div class="muted">待搬 m2 6.1 清單 / 搜尋 / filter</div></div><div class="panel"><h3>匯出 / Soft Delete</h3><button class="light">匯出 JSON</button> <button class="light">Soft Delete</button><div class="muted" style="margin-top:8px">保留舊 M2 作業邏輯，暫不寫回。</div></div></div>`}
function runHoldingZonesAction(action,key){
  setModule('zones');
  setTimeout(()=>{
    if(action==='nav'){
      const el=document.getElementById(`hz-zone-${key}`)||(key==='healthy'?document.querySelector('.hz-healthy-wrap'):null);
      if(key==='healthy')document.querySelector('.hz-healthy-wrap')?.setAttribute('open','open');
      (el||document.getElementById('bottomQuery'))?.scrollIntoView({behavior:'smooth',block:'start'});
      return;
    }
    if(action==='expand-all')document.querySelectorAll('.hz-card').forEach(c=>c.classList.add('open'));
    if(action==='collapse-all')document.querySelectorAll('.hz-card').forEach(c=>c.classList.remove('open'));
    if(action==='risk-only')document.querySelectorAll('.hz-card').forEach(c=>{
      c.classList.toggle('open',c.classList.contains('hz-card-danger')||c.classList.contains('hz-card-watch')||c.classList.contains('hz-card-exit'));
    });
    document.getElementById('bottomQuery')?.scrollIntoView({behavior:'smooth',block:'start'});
  },240);
}
window.runM2HoldingZonesAction=runHoldingZonesAction;

function bindMenu(){document.querySelectorAll('.menu-btn').forEach(btn=>btn.addEventListener('click',()=>setModule(btn.dataset.module)))}
function bindFilters(){['fcnSearch','fcnTagFilter','stockLightFilter'].forEach(id=>{const el=document.getElementById(id);if(el)el.oninput=renderManagementTables;if(el)el.onchange=renderManagementTables})}
async function loadData(){try{runtimeMeta.textContent='載入資料中...';const [poolRes,marketRes,pool30Res,marketFuturesRes,m8SurfaceRes]=await Promise.all([fetch('../../data/fcn_pool.json'),fetch('../../data/market_runtime.json'),fetch('../../data/pool30.json'),fetch('../../data/mm/market_fcn_history.json').catch(()=>null),fetch('../../data/mm/m8_template_surface.json').catch(()=>null)]);const fcnPool=await poolRes.json(),marketRuntime=await marketRes.json(),pool30=await pool30Res.json();marketHistory=marketFuturesRes&&marketFuturesRes.ok?await marketFuturesRes.json():[];m8Surface=m8SurfaceRes&&m8SurfaceRes.ok?await m8SurfaceRes.json():null;poolMap={};pool30.forEach(p=>poolMap[p.symbol]=p);runtime=runM2HealthEngine({fcnPool,marketRuntime:marketRuntime.rows||marketRuntime,pool30});buildPlannerRows(runtime.fcns);buildStockCapacityRows();renderTopDashboard();renderCurrentModule();runtimeMeta.innerHTML=`最後更新：${marketRuntime.generated_at||'unknown'}｜Active FCN ${runtime.total} 檔｜Stock Exposure ${runtime.stockMap.length} 檔`;}catch(err){console.error(err);runtimeMeta.innerHTML=`<span class="bad">載入失敗：${err.message}</span>`}}
runBtn.addEventListener('click',loadData);reloadBtn.addEventListener('click',loadData);bindMenu();bindMaturitySubnav();loadData();






