(function(){
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString('en-US',{maximumFractionDigits:d}):'-';
const pct=(v,d=2)=>Number.isFinite(Number(v))?`${fmt(v,d)}%`:'-';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function css(){return `<style>.bdui{display:grid;gap:14px}.bdui-shell{display:grid;grid-template-columns:260px 1fr;gap:14px;align-items:start}.bdui-left{display:grid;gap:10px;position:sticky;top:10px}.bdui-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:14px;box-shadow:0 2px 8px rgba(15,23,42,.04)}.bdui-card h3{margin:0 0 8px;font-size:17px}.bdui-sub{font-size:13px;color:#64748b;line-height:1.55}.bdui-list{display:grid;gap:8px;max-height:560px;overflow:auto}.bdui-item{border:1px solid #e5e7eb;border-radius:14px;background:#fff;padding:10px;cursor:pointer}.bdui-item.active{outline:3px solid #bfdbfe;background:#f8fbff}.bdui-item b{display:block;font-size:13px;word-break:break-word}.bdui-main{display:grid;gap:12px}.bdui-analysis{display:grid;grid-template-columns:1.2fr repeat(3,1fr);gap:10px}.bdui-kpi{background:#f8fafc;border:1px solid #e5e7eb;border-radius:14px;padding:10px}.bdui-kpi label{display:block;font-size:11px;color:#64748b;font-weight:900}.bdui-kpi strong{display:block;font-size:18px;color:#0f172a}.bdui-comment{border:1px solid #dbeafe;background:#f8fbff;border-radius:14px;padding:12px;font-size:14px;line-height:1.7;color:#334155}.bdui-chip{display:inline-block;border-radius:999px;padding:4px 8px;margin-top:6px;font-size:12px;font-weight:900;background:#f1f5f9;color:#334155}.bdui-chip.update{background:#ffedd5;color:#9a3412}.bdui-chip.watch{background:#fef9c3;color:#854d0e}.bdui-chip.promote{background:#dcfce7;color:#166534}.bdui-chip.recalibrate{background:#fee2e2;color:#991b1b}.bdui-chip.normal{background:#dbeafe;color:#1e3a8a}.bdui-details{border:1px solid #e5e7eb;border-radius:16px;background:#fff;padding:12px}.bdui-details summary{font-weight:950;cursor:pointer}.bdui-small-grid{display:grid;grid-template-columns:repeat(3,minmax(220px,1fr));gap:10px;margin-top:10px}.bdui-small{border:1px solid #e5e7eb;border-radius:16px;background:#fff;padding:12px}.bdui-small-title{font-size:15px;font-weight:950;word-break:break-word}.bdui-kv{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0}.bdui-kv div{background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;padding:8px}.bdui-kv label{display:block;font-size:11px;color:#64748b;font-weight:900}.bdui-kv strong{display:block;font-size:16px;color:#0f172a}.bdui-table{width:100%;border-collapse:collapse;font-size:12px;min-width:800px}.bdui-table th,.bdui-table td{border-bottom:1px solid #e5e7eb;padding:7px;text-align:left}.bdui-table th{background:#f8fafc}.bdui-table-wrap{overflow:auto}@media(max-width:1100px){.bdui-shell,.bdui-analysis,.bdui-small-grid{grid-template-columns:1fr}.bdui-left{position:static}}</style>`}
function actionFor(count,gap){count=n(count,0);gap=n(gap,0);if(count>=5&&Math.abs(gap)<=1)return{key:'promote',label:'Promote',text:'樣本足且貼近市場，可作主力小模板。'};if(count>=3&&Math.abs(gap)>3)return{key:'recalibrate',label:'Recalibrate',text:'樣本足但偏離大，應進入校正清單。'};if(count>=3)return{key:'update',label:'Update Candidate',text:'樣本達標，可列入 surface 更新候選。'};return{key:'watch',label:'Watch',text:'樣本不足，先觀察。'} }
function templateState(t){const gap=n(t.gap_final_pct,0),count=n(t.count,0);if(count<3)return{key:'watch',text:'樣本不足'};if(gap>3)return{key:'update',text:'市場偏甜'};if(gap<-3)return{key:'recalibrate',text:'市場偏貴'};return{key:'normal',text:'接近市場'}}
function sortTemplates(list){return [...(list||[])].sort((a,b)=>n(b.count,0)-n(a.count,0));}
function radarScore(r){const a=String(r.action||r.coverage||'').toLowerCase();if(a.includes('recal'))return 1;if(a.includes('promote'))return 2;if(a.includes('update')||a.includes('candidate'))return 3;if(a.includes('watch'))return 4;return 5}
function sortRadar(list){return [...(list||[])].sort((a,b)=>radarScore(a)-radarScore(b)||n(b.count,0)-n(a.count,0));}
function rowsDesc(t){return `${n(t.count,0)} rows｜Mkt ${pct(t.market,2)}｜Final ${pct(t.final_fair,2)}｜Gap ${pct(t.gap_final_pct,2)}`}
function renderTemplateList(summary,idx){return `<div class="bdui-list">${summary.map((t,i)=>{const st=templateState(t);return `<div class="bdui-item ${i===idx?'active':''}" data-bdui-template="${i}"><b>${esc(t.template)}</b><div class="bdui-sub">${rowsDesc(t)}</div><span class="bdui-chip ${st.key}">${st.text}</span></div>`}).join('')||'<div class="bdui-sub">No template rows.</div>'}</div>`}
function renderRadarList(radar,idx){return `<div class="bdui-list">${radar.map((r,i)=>{const gap=n(r.gap_after_pct??r.gap_final_pct,0);const a=actionFor(r.count,gap);return `<div class="bdui-item ${i===idx?'active':''}" data-bdui-radar="${i}"><b>${esc(r.key)}</b><div class="bdui-sub">${esc(r.parent_template||'-')}｜${n(r.count,0)} rows｜Mkt ${pct(r.market,2)}</div><span class="bdui-chip ${a.key}">${esc(r.action||a.label)}</span></div>`}).join('')||'<div class="bdui-sub">No radar rows.</div>'}</div>`}
function renderRows(rows){return `<div class="bdui-table-wrap"><table class="bdui-table"><thead><tr><th>FCN</th><th>Basket</th><th>Market</th><th>Final</th><th>Strike/KI</th><th>Tenor</th></tr></thead><tbody>${(rows||[]).slice(0,40).map(r=>`<tr><td>${esc(r.fcn_id)}</td><td>${esc(r.basket)}</td><td>${pct(r.market_coupon,2)}</td><td>${pct(r.final_fair,2)}</td><td>${fmt(r.strike,1)} / ${fmt(r.ki,1)}</td><td>${r.tenor||'-'}</td></tr>`).join('')}</tbody></table></div>`}
function renderSmallCard(s){const a=actionFor(s.count,s.gap_after_pct);return `<div class="bdui-small"><div class="bdui-small-title">${esc(s.key)}</div><span class="bdui-chip ${a.key}">${a.label}</span><div class="bdui-kv"><div><label>Rows</label><strong>${s.count||0}</strong></div><div><label>Market</label><strong>${pct(s.market,2)}</strong></div><div><label>Final AVG</label><strong>${pct(s.final_fair,2)}</strong></div><div><label>New Fair</label><strong>${pct(s.new_fair,2)}</strong></div><div><label>Gap</label><strong>${pct(s.gap_after_pct,2)}</strong></div><div><label>Type</label><strong>${esc(s.group_type||'-')}</strong></div></div><div class="bdui-comment">${a.text}</div><details><summary>Included rows</summary>${renderRows(s.included_rows||[])}</details></div>`}
function templateAnalysis(t){if(!t)return '<div class="bdui-card">No template selected.</div>';const st=templateState(t),a=actionFor(t.count,t.gap_final_pct);return `<div class="bdui-main"><div class="bdui-card"><h3>What happened｜${esc(t.template)}</h3><div class="bdui-analysis"><div class="bdui-comment"><b>${st.text}</b>：Market AVG ${pct(t.market,2)}，Final AVG ${pct(t.final_fair,2)}，Gap ${pct(t.gap_final_pct,2)}。${a.text}</div><div class="bdui-kpi"><label>Rows</label><strong>${n(t.count,0)}</strong></div><div class="bdui-kpi"><label>Market AVG</label><strong>${pct(t.market,2)}</strong></div><div class="bdui-kpi"><label>Action</label><strong>${a.label}</strong></div></div></div><details class="bdui-details"><summary>Small-template status｜default hidden</summary><div class="bdui-small-grid">${(t.subtemplates||[]).map(renderSmallCard).join('')||'<div class="bdui-sub">No subtemplates.</div>'}</div></details></div>`}
function findSubByKey(summary,key){for(const t of summary){const s=(t.subtemplates||[]).find(x=>String(x.key)===String(key));if(s)return{s,parent:t};}return{}}
function radarAnalysis(r,summary){if(!r)return '<div class="bdui-card">No radar selected.</div>';const found=findSubByKey(summary,r.key);const s=found.s||r;const gap=n(s.gap_after_pct??r.gap_after_pct??r.gap_final_pct,0);const a=actionFor(s.count??r.count,gap);return `<div class="bdui-main"><div class="bdui-card"><h3>Radar Action｜${esc(r.key)}</h3><div class="bdui-analysis"><div class="bdui-comment"><b>${esc(r.action||a.label)}</b>：${esc(r.reason||a.text)} Parent template：${esc(r.parent_template||found.parent?.template||'-')}。建議：${a.text}</div><div class="bdui-kpi"><label>Rows</label><strong>${n(s.count??r.count,0)}</strong></div><div class="bdui-kpi"><label>Market</label><strong>${pct(s.market??r.market,2)}</strong></div><div class="bdui-kpi"><label>Gap</label><strong>${pct(gap,2)}</strong></div></div></div><details class="bdui-details"><summary>Included rows｜default hidden</summary>${renderRows(s.included_rows||[])}</details></div>`}
function executive(summary){const total=summary.reduce((s,t)=>s+n(t.count,0),0);const avgGap=summary.length?summary.reduce((s,t)=>s+n(t.gap_final_pct,0)*n(t.count,1),0)/Math.max(1,total):0;return{total,avgGap,state:avgGap>2?'整體偏甜':avgGap<-2?'整體偏貴':'整體接近市場'}}
function renderBoard(workspace={},state={mode:'b1',index:0}){if(typeof state==='number')state={mode:'b1',index:state};const mode=state.mode||'b1';const idx=n(state.index,0);const embedded=!!state.embedded;const summary=sortTemplates(workspace.templateSummary||[]);const radar=sortRadar(workspace.radar||[]);const ex=executive(summary);const right=mode==='b2'?radarAnalysis(radar[idx],summary):templateAnalysis(summary[idx]);const title=mode==='b2'?'B2. Template Update Radar':'B1. Template List';const left=mode==='b2'?renderRadarList(radar,idx):renderTemplateList(summary,idx);const head=embedded?`<div class="bdui-card"><h3>${title}</h3><div class="bdui-sub">${esc(ex.state)}｜Rows ${ex.total}｜Weighted Gap ${pct(ex.avgGap,2)}</div></div>`:`<div class="bdui-card"><h3>B. Batch Market Workspace</h3><div class="bdui-sub">${esc(ex.state)}｜Rows ${ex.total}｜Weighted Gap ${pct(ex.avgGap,2)}</div></div>`;return `${css()}<div class="bdui">${head}<div class="bdui-shell"><aside class="bdui-left">${left}</aside><main>${right}</main></div></div>`}
window.renderM8BatchDecisionBoard=renderBoard;
})();
